-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_4k_ssr2_i16_c16_t16_top_fft_serial_kernel_wrapper is
port (
    twiddle_out1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    twiddle_out1_empty_n : IN STD_LOGIC;
    twiddle_out1_read : OUT STD_LOGIC;
    fft2_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    fft2_out1_full_n : IN STD_LOGIC;
    fft2_out1_write : OUT STD_LOGIC;
    iter_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    iter_empty_n : IN STD_LOGIC;
    iter_read : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of fft_4k_ssr2_i16_c16_t16_top_fft_serial_kernel_wrapper is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal entry_proc107_U0_ap_start : STD_LOGIC;
    signal entry_proc107_U0_ap_done : STD_LOGIC;
    signal entry_proc107_U0_ap_continue : STD_LOGIC;
    signal entry_proc107_U0_ap_idle : STD_LOGIC;
    signal entry_proc107_U0_ap_ready : STD_LOGIC;
    signal entry_proc107_U0_return_r : STD_LOGIC_VECTOR (31 downto 0);
    signal entry_proc107_U0_iter_read : STD_LOGIC;
    signal p_channel_full_n : STD_LOGIC;
    signal fft_serial_kernel_U0_twiddle_out1_read : STD_LOGIC;
    signal fft_serial_kernel_U0_fft2_out1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_serial_kernel_U0_fft2_out1_write : STD_LOGIC;
    signal fft_serial_kernel_U0_ap_start : STD_LOGIC;
    signal fft_serial_kernel_U0_ap_done : STD_LOGIC;
    signal fft_serial_kernel_U0_ap_ready : STD_LOGIC;
    signal fft_serial_kernel_U0_ap_idle : STD_LOGIC;
    signal fft_serial_kernel_U0_ap_continue : STD_LOGIC;
    signal p_channel_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal p_channel_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal p_channel_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal p_channel_empty_n : STD_LOGIC;

    component fft_4k_ssr2_i16_c16_t16_top_entry_proc107 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        return_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        iter_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        iter_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        iter_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        iter_empty_n : IN STD_LOGIC;
        iter_read : OUT STD_LOGIC );
    end component;


    component fft_4k_ssr2_i16_c16_t16_top_fft_serial_kernel IS
    port (
        twiddle_out1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        twiddle_out1_empty_n : IN STD_LOGIC;
        twiddle_out1_read : OUT STD_LOGIC;
        fft2_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fft2_out1_full_n : IN STD_LOGIC;
        fft2_out1_write : OUT STD_LOGIC;
        iter : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component fft_4k_ssr2_i16_c16_t16_top_fifo_w32_d2_S_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    entry_proc107_U0 : component fft_4k_ssr2_i16_c16_t16_top_entry_proc107
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => entry_proc107_U0_ap_start,
        ap_done => entry_proc107_U0_ap_done,
        ap_continue => entry_proc107_U0_ap_continue,
        ap_idle => entry_proc107_U0_ap_idle,
        ap_ready => entry_proc107_U0_ap_ready,
        return_r => entry_proc107_U0_return_r,
        iter_dout => iter_dout,
        iter_num_data_valid => ap_const_lv3_0,
        iter_fifo_cap => ap_const_lv3_0,
        iter_empty_n => iter_empty_n,
        iter_read => entry_proc107_U0_iter_read);

    fft_serial_kernel_U0 : component fft_4k_ssr2_i16_c16_t16_top_fft_serial_kernel
    port map (
        twiddle_out1_dout => twiddle_out1_dout,
        twiddle_out1_empty_n => twiddle_out1_empty_n,
        twiddle_out1_read => fft_serial_kernel_U0_twiddle_out1_read,
        fft2_out1_din => fft_serial_kernel_U0_fft2_out1_din,
        fft2_out1_full_n => fft2_out1_full_n,
        fft2_out1_write => fft_serial_kernel_U0_fft2_out1_write,
        iter => p_channel_dout,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => fft_serial_kernel_U0_ap_start,
        ap_done => fft_serial_kernel_U0_ap_done,
        ap_ready => fft_serial_kernel_U0_ap_ready,
        ap_idle => fft_serial_kernel_U0_ap_idle,
        ap_continue => fft_serial_kernel_U0_ap_continue);

    p_channel_U : component fft_4k_ssr2_i16_c16_t16_top_fifo_w32_d2_S_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc107_U0_return_r,
        if_full_n => p_channel_full_n,
        if_write => entry_proc107_U0_ap_done,
        if_dout => p_channel_dout,
        if_num_data_valid => p_channel_num_data_valid,
        if_fifo_cap => p_channel_fifo_cap,
        if_empty_n => p_channel_empty_n,
        if_read => fft_serial_kernel_U0_ap_ready);




    ap_done <= fft_serial_kernel_U0_ap_done;
    ap_idle <= (fft_serial_kernel_U0_ap_idle and (p_channel_empty_n xor ap_const_logic_1) and entry_proc107_U0_ap_idle);
    ap_ready <= entry_proc107_U0_ap_ready;
    entry_proc107_U0_ap_continue <= p_channel_full_n;
    entry_proc107_U0_ap_start <= ap_start;
    fft2_out1_din <= fft_serial_kernel_U0_fft2_out1_din;
    fft2_out1_write <= fft_serial_kernel_U0_fft2_out1_write;
    fft_serial_kernel_U0_ap_continue <= ap_continue;
    fft_serial_kernel_U0_ap_start <= p_channel_empty_n;
    iter_read <= entry_proc107_U0_iter_read;
    twiddle_out1_read <= fft_serial_kernel_U0_twiddle_out1_read;
end behav;
