// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_16k_ssr2_i14_c16_t18_top_dataflow_in_loop_VITIS_LOOP_310_1_133 (
        twiddle_out1_dout,
        twiddle_out1_empty_n,
        twiddle_out1_read,
        fft2_out1_din,
        fft2_out1_full_n,
        fft2_out1_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] twiddle_out1_dout;
input   twiddle_out1_empty_n;
output   twiddle_out1_read;
output  [31:0] fft2_out1_din;
input   fft2_out1_full_n;
output   fft2_out1_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    Block_newFuncRoot_proc_proc17_U0_ap_start;
wire    Block_newFuncRoot_proc_proc17_U0_ap_done;
wire    Block_newFuncRoot_proc_proc17_U0_ap_continue;
wire    Block_newFuncRoot_proc_proc17_U0_ap_idle;
wire    Block_newFuncRoot_proc_proc17_U0_ap_ready;
wire   [15:0] Block_newFuncRoot_proc_proc17_U0_empty;
wire    empty_full_n;
wire    Block_newFuncRoot_proc_proc18_U0_ap_start;
wire    Block_newFuncRoot_proc_proc18_U0_ap_done;
wire    Block_newFuncRoot_proc_proc18_U0_ap_continue;
wire    Block_newFuncRoot_proc_proc18_U0_ap_idle;
wire    Block_newFuncRoot_proc_proc18_U0_ap_ready;
wire    Block_newFuncRoot_proc_proc18_U0_start_out;
wire    Block_newFuncRoot_proc_proc18_U0_start_write;
wire   [15:0] Block_newFuncRoot_proc_proc18_U0_fft_config_din;
wire    Block_newFuncRoot_proc_proc18_U0_fft_config_write;
wire    fft_fft_params_U0_twiddle_out1_read;
wire   [31:0] fft_fft_params_U0_fft2_out1_din;
wire    fft_fft_params_U0_fft2_out1_write;
wire   [7:0] fft_fft_params_U0_fft_status_din;
wire    fft_fft_params_U0_fft_status_write;
wire    fft_fft_params_U0_fft_config_read;
wire    fft_fft_params_U0_ap_ready;
wire    Block_newFuncRoot_proc_proc19_U0_ap_start;
wire    Block_newFuncRoot_proc_proc19_U0_ap_done;
wire    Block_newFuncRoot_proc_proc19_U0_ap_continue;
wire    Block_newFuncRoot_proc_proc19_U0_ap_idle;
wire    Block_newFuncRoot_proc_proc19_U0_ap_ready;
wire    Block_newFuncRoot_proc_proc19_U0_fft_status_read;
wire   [15:0] empty_dout;
wire   [2:0] empty_num_data_valid;
wire   [2:0] empty_fifo_cap;
wire    empty_empty_n;
wire    fft_config_full_n;
wire   [15:0] fft_config_dout;
wire   [2:0] fft_config_num_data_valid;
wire   [2:0] fft_config_fifo_cap;
wire    fft_config_empty_n;
wire    fft_status_full_n;
wire   [7:0] fft_status_dout;
wire   [2:0] fft_status_num_data_valid;
wire   [2:0] fft_status_fifo_cap;
wire    fft_status_empty_n;
wire   [0:0] start_for_Block_newFuncRoot_proc_proc19_U0_din;
wire    start_for_Block_newFuncRoot_proc_proc19_U0_full_n;
wire   [0:0] start_for_Block_newFuncRoot_proc_proc19_U0_dout;
wire    start_for_Block_newFuncRoot_proc_proc19_U0_empty_n;

fft_16k_ssr2_i14_c16_t18_top_Block_newFuncRoot_proc_proc17 Block_newFuncRoot_proc_proc17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_newFuncRoot_proc_proc17_U0_ap_start),
    .ap_done(Block_newFuncRoot_proc_proc17_U0_ap_done),
    .ap_continue(Block_newFuncRoot_proc_proc17_U0_ap_continue),
    .ap_idle(Block_newFuncRoot_proc_proc17_U0_ap_idle),
    .ap_ready(Block_newFuncRoot_proc_proc17_U0_ap_ready),
    .empty(Block_newFuncRoot_proc_proc17_U0_empty)
);

fft_16k_ssr2_i14_c16_t18_top_Block_newFuncRoot_proc_proc18 Block_newFuncRoot_proc_proc18_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_newFuncRoot_proc_proc18_U0_ap_start),
    .start_full_n(start_for_Block_newFuncRoot_proc_proc19_U0_full_n),
    .ap_done(Block_newFuncRoot_proc_proc18_U0_ap_done),
    .ap_continue(Block_newFuncRoot_proc_proc18_U0_ap_continue),
    .ap_idle(Block_newFuncRoot_proc_proc18_U0_ap_idle),
    .ap_ready(Block_newFuncRoot_proc_proc18_U0_ap_ready),
    .start_out(Block_newFuncRoot_proc_proc18_U0_start_out),
    .start_write(Block_newFuncRoot_proc_proc18_U0_start_write),
    .fft_config_din(Block_newFuncRoot_proc_proc18_U0_fft_config_din),
    .fft_config_num_data_valid(fft_config_num_data_valid),
    .fft_config_fifo_cap(fft_config_fifo_cap),
    .fft_config_full_n(fft_config_full_n),
    .fft_config_write(Block_newFuncRoot_proc_proc18_U0_fft_config_write),
    .empty(empty_dout)
);

fft_16k_ssr2_i14_c16_t18_top_fft_fft_params_s fft_fft_params_U0(
    .twiddle_out1_dout(twiddle_out1_dout),
    .twiddle_out1_empty_n(twiddle_out1_empty_n),
    .twiddle_out1_read(fft_fft_params_U0_twiddle_out1_read),
    .fft2_out1_din(fft_fft_params_U0_fft2_out1_din),
    .fft2_out1_full_n(fft2_out1_full_n),
    .fft2_out1_write(fft_fft_params_U0_fft2_out1_write),
    .fft_status_din(fft_fft_params_U0_fft_status_din),
    .fft_status_full_n(fft_status_full_n),
    .fft_status_write(fft_fft_params_U0_fft_status_write),
    .fft_config_dout(fft_config_dout),
    .fft_config_empty_n(fft_config_empty_n),
    .fft_config_read(fft_fft_params_U0_fft_config_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ready(fft_fft_params_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_Block_newFuncRoot_proc_proc19 Block_newFuncRoot_proc_proc19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_newFuncRoot_proc_proc19_U0_ap_start),
    .ap_done(Block_newFuncRoot_proc_proc19_U0_ap_done),
    .ap_continue(Block_newFuncRoot_proc_proc19_U0_ap_continue),
    .ap_idle(Block_newFuncRoot_proc_proc19_U0_ap_idle),
    .ap_ready(Block_newFuncRoot_proc_proc19_U0_ap_ready),
    .fft_status_dout(fft_status_dout),
    .fft_status_num_data_valid(fft_status_num_data_valid),
    .fft_status_fifo_cap(fft_status_fifo_cap),
    .fft_status_empty_n(fft_status_empty_n),
    .fft_status_read(Block_newFuncRoot_proc_proc19_U0_fft_status_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w16_d2_S_x empty_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_newFuncRoot_proc_proc17_U0_empty),
    .if_full_n(empty_full_n),
    .if_write(Block_newFuncRoot_proc_proc17_U0_ap_done),
    .if_dout(empty_dout),
    .if_num_data_valid(empty_num_data_valid),
    .if_fifo_cap(empty_fifo_cap),
    .if_empty_n(empty_empty_n),
    .if_read(Block_newFuncRoot_proc_proc18_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w16_d2_S_x fft_config_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_newFuncRoot_proc_proc18_U0_fft_config_din),
    .if_full_n(fft_config_full_n),
    .if_write(Block_newFuncRoot_proc_proc18_U0_fft_config_write),
    .if_dout(fft_config_dout),
    .if_num_data_valid(fft_config_num_data_valid),
    .if_fifo_cap(fft_config_fifo_cap),
    .if_empty_n(fft_config_empty_n),
    .if_read(fft_fft_params_U0_fft_config_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w8_d2_S_x fft_status_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_fft_params_U0_fft_status_din),
    .if_full_n(fft_status_full_n),
    .if_write(fft_fft_params_U0_fft_status_write),
    .if_dout(fft_status_dout),
    .if_num_data_valid(fft_status_num_data_valid),
    .if_fifo_cap(fft_status_fifo_cap),
    .if_empty_n(fft_status_empty_n),
    .if_read(Block_newFuncRoot_proc_proc19_U0_fft_status_read)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_Block_newFuncRoot_proc_proc19_U0 start_for_Block_newFuncRoot_proc_proc19_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_newFuncRoot_proc_proc19_U0_din),
    .if_full_n(start_for_Block_newFuncRoot_proc_proc19_U0_full_n),
    .if_write(Block_newFuncRoot_proc_proc18_U0_start_write),
    .if_dout(start_for_Block_newFuncRoot_proc_proc19_U0_dout),
    .if_empty_n(start_for_Block_newFuncRoot_proc_proc19_U0_empty_n),
    .if_read(Block_newFuncRoot_proc_proc19_U0_ap_ready)
);

assign Block_newFuncRoot_proc_proc17_U0_ap_continue = empty_full_n;

assign Block_newFuncRoot_proc_proc17_U0_ap_start = ap_start;

assign Block_newFuncRoot_proc_proc18_U0_ap_continue = 1'b1;

assign Block_newFuncRoot_proc_proc18_U0_ap_start = empty_empty_n;

assign Block_newFuncRoot_proc_proc19_U0_ap_continue = ap_continue;

assign Block_newFuncRoot_proc_proc19_U0_ap_start = start_for_Block_newFuncRoot_proc_proc19_U0_empty_n;

assign ap_done = Block_newFuncRoot_proc_proc19_U0_ap_done;

assign ap_idle = ((empty_empty_n ^ 1'b1) & Block_newFuncRoot_proc_proc19_U0_ap_idle & Block_newFuncRoot_proc_proc18_U0_ap_idle & Block_newFuncRoot_proc_proc17_U0_ap_idle);

assign ap_ready = Block_newFuncRoot_proc_proc17_U0_ap_ready;

assign fft2_out1_din = fft_fft_params_U0_fft2_out1_din;

assign fft2_out1_write = fft_fft_params_U0_fft2_out1_write;

assign start_for_Block_newFuncRoot_proc_proc19_U0_din = 1'b1;

assign twiddle_out1_read = fft_fft_params_U0_twiddle_out1_read;

endmodule //fft_16k_ssr2_i14_c16_t18_top_dataflow_in_loop_VITIS_LOOP_310_1_133
