// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_16k_ssr2_i14_c16_t18_top_twiddle_Pipeline_VITIS_LOOP_264_1_VITIS_LOOP_267_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fft1_out_dout,
        fft1_out_num_data_valid,
        fft1_out_fifo_cap,
        fft1_out_empty_n,
        fft1_out_read,
        twiddle_out0_din,
        twiddle_out0_num_data_valid,
        twiddle_out0_fifo_cap,
        twiddle_out0_full_n,
        twiddle_out0_write,
        twiddle_out1_din,
        twiddle_out1_num_data_valid,
        twiddle_out1_fifo_cap,
        twiddle_out1_full_n,
        twiddle_out1_write,
        bound
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] fft1_out_dout;
input  [2:0] fft1_out_num_data_valid;
input  [2:0] fft1_out_fifo_cap;
input   fft1_out_empty_n;
output   fft1_out_read;
output  [31:0] twiddle_out0_din;
input  [2:0] twiddle_out0_num_data_valid;
input  [2:0] twiddle_out0_fifo_cap;
input   twiddle_out0_full_n;
output   twiddle_out0_write;
output  [31:0] twiddle_out1_din;
input  [2:0] twiddle_out1_num_data_valid;
input  [2:0] twiddle_out1_fifo_cap;
input   twiddle_out1_full_n;
output   twiddle_out1_write;
input  [44:0] bound;

reg ap_idle;
reg fft1_out_read;
reg twiddle_out0_write;
reg twiddle_out1_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln264_fu_124_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    fft1_out_blk_n;
wire    ap_block_pp0_stage0;
reg    twiddle_out0_blk_n;
reg    twiddle_out1_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln264_reg_295;
wire  signed [31:0] sext_ln50_fu_201_p1;
wire  signed [31:0] sext_ln50_2_fu_209_p1;
wire  signed [31:0] sext_ln50_3_fu_213_p1;
wire   [31:0] mul_ln50_fu_217_p2;
reg   [31:0] mul_ln50_reg_315;
reg  signed [31:0] mul_ln50_reg_315_pp0_iter4_reg;
wire   [31:0] mul_ln51_fu_223_p2;
reg   [31:0] mul_ln51_reg_320;
reg  signed [31:0] mul_ln51_reg_320_pp0_iter4_reg;
wire   [31:0] trunc_ln274_fu_229_p1;
reg   [31:0] trunc_ln274_reg_325;
reg   [31:0] trunc_ln274_reg_325_pp0_iter4_reg;
reg   [31:0] trunc_ln274_reg_325_pp0_iter5_reg;
wire    grp_get_phase_factor_fu_104_ap_start;
wire    grp_get_phase_factor_fu_104_ap_done;
wire    grp_get_phase_factor_fu_104_ap_idle;
wire    grp_get_phase_factor_fu_104_ap_ready;
reg    grp_get_phase_factor_fu_104_ap_ce;
wire   [12:0] grp_get_phase_factor_fu_104_i;
wire   [17:0] grp_get_phase_factor_fu_104_ap_return_0;
wire   [17:0] grp_get_phase_factor_fu_104_ap_return_1;
reg    ap_block_state4_pp0_stage0_iter3_ignore_call10;
reg    ap_block_state7_pp0_stage0_iter6_ignore_call10;
reg    ap_block_pp0_stage0_11001_ignoreCallOp27;
reg    grp_get_phase_factor_fu_104_ap_start_reg;
reg   [13:0] i_fu_70;
wire   [13:0] i_1_fu_162_p2;
wire    ap_loop_init;
reg   [44:0] indvar_flatten_fu_74;
wire   [44:0] add_ln264_fu_129_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln267_fu_143_p2;
wire   [13:0] select_ln264_fu_149_p3;
wire   [15:0] temp_data1_M_real_fu_173_p4;
wire   [15:0] temp_data1_M_imag_fu_183_p4;
wire  signed [17:0] mul_ln50_fu_217_p0;
wire  signed [15:0] mul_ln50_fu_217_p1;
wire  signed [31:0] sext_ln50_1_fu_205_p1;
wire  signed [17:0] mul_ln51_fu_223_p0;
wire  signed [15:0] mul_ln51_fu_223_p1;
wire  signed [31:0] grp_fu_260_p3;
wire  signed [31:0] grp_fu_268_p3;
wire   [15:0] trunc_ln275_1_fu_242_p4;
wire   [15:0] trunc_ln1_fu_233_p4;
wire  signed [17:0] grp_fu_260_p0;
wire  signed [15:0] grp_fu_260_p1;
wire  signed [17:0] grp_fu_268_p0;
wire  signed [15:0] grp_fu_268_p1;
reg    grp_fu_260_ce;
reg    grp_fu_268_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 grp_get_phase_factor_fu_104_ap_start_reg = 1'b0;
#0 i_fu_70 = 14'd0;
#0 indvar_flatten_fu_74 = 45'd0;
#0 ap_done_reg = 1'b0;
end

fft_16k_ssr2_i14_c16_t18_top_get_phase_factor grp_get_phase_factor_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_get_phase_factor_fu_104_ap_start),
    .ap_done(grp_get_phase_factor_fu_104_ap_done),
    .ap_idle(grp_get_phase_factor_fu_104_ap_idle),
    .ap_ready(grp_get_phase_factor_fu_104_ap_ready),
    .ap_ce(grp_get_phase_factor_fu_104_ap_ce),
    .i(grp_get_phase_factor_fu_104_i),
    .ap_return_0(grp_get_phase_factor_fu_104_ap_return_0),
    .ap_return_1(grp_get_phase_factor_fu_104_ap_return_1)
);

fft_16k_ssr2_i14_c16_t18_top_mul_18s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_18s_16s_32_1_1_U31(
    .din0(mul_ln50_fu_217_p0),
    .din1(mul_ln50_fu_217_p1),
    .dout(mul_ln50_fu_217_p2)
);

fft_16k_ssr2_i14_c16_t18_top_mul_18s_16s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_18s_16s_32_1_1_U32(
    .din0(mul_ln51_fu_223_p0),
    .din1(mul_ln51_fu_223_p1),
    .dout(mul_ln51_fu_223_p2)
);

fft_16k_ssr2_i14_c16_t18_top_mac_mulsub_18s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_mulsub_18s_16s_32s_32_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_260_p0),
    .din1(grp_fu_260_p1),
    .din2(mul_ln50_reg_315_pp0_iter4_reg),
    .ce(grp_fu_260_ce),
    .dout(grp_fu_260_p3)
);

fft_16k_ssr2_i14_c16_t18_top_mac_muladd_18s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_18s_16s_32s_32_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_268_p0),
    .din1(grp_fu_268_p1),
    .din2(mul_ln51_reg_320_pp0_iter4_reg),
    .ce(grp_fu_268_ce),
    .dout(grp_fu_268_p3)
);

fft_16k_ssr2_i14_c16_t18_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_get_phase_factor_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln264_fu_124_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_get_phase_factor_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_get_phase_factor_fu_104_ap_ready == 1'b1)) begin
            grp_get_phase_factor_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            i_fu_70 <= 14'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_70 <= i_1_fu_162_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_74 <= 45'd0;
        end else if (((icmp_ln264_fu_124_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_74 <= add_ln264_fu_129_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln264_reg_295 <= icmp_ln264_fu_124_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        mul_ln50_reg_315 <= mul_ln50_fu_217_p2;
        mul_ln50_reg_315_pp0_iter4_reg <= mul_ln50_reg_315;
        mul_ln51_reg_320 <= mul_ln51_fu_223_p2;
        mul_ln51_reg_320_pp0_iter4_reg <= mul_ln51_reg_320;
        trunc_ln274_reg_325 <= trunc_ln274_fu_229_p1;
        trunc_ln274_reg_325_pp0_iter4_reg <= trunc_ln274_reg_325;
        trunc_ln274_reg_325_pp0_iter5_reg <= trunc_ln274_reg_325_pp0_iter4_reg;
    end
end

always @ (*) begin
    if (((icmp_ln264_fu_124_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        fft1_out_blk_n = fft1_out_empty_n;
    end else begin
        fft1_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        fft1_out_read = 1'b1;
    end else begin
        fft1_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_260_ce = 1'b1;
    end else begin
        grp_fu_260_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_268_ce = 1'b1;
    end else begin
        grp_fu_268_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp27) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_get_phase_factor_fu_104_ap_ce = 1'b1;
    end else begin
        grp_get_phase_factor_fu_104_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        twiddle_out0_blk_n = twiddle_out0_full_n;
    end else begin
        twiddle_out0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        twiddle_out0_write = 1'b1;
    end else begin
        twiddle_out0_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        twiddle_out1_blk_n = twiddle_out1_full_n;
    end else begin
        twiddle_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        twiddle_out1_write = 1'b1;
    end else begin
        twiddle_out1_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln264_fu_129_p2 = (indvar_flatten_fu_74 + 45'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp27 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_ignore_call10)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3_ignore_call10)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = (fft1_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3_ignore_call10 = (fft1_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((twiddle_out1_full_n == 1'b0) | (twiddle_out0_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6_ignore_call10 = ((twiddle_out1_full_n == 1'b0) | (twiddle_out0_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign grp_fu_260_p0 = sext_ln50_2_fu_209_p1;

assign grp_fu_260_p1 = sext_ln50_3_fu_213_p1;

assign grp_fu_268_p0 = sext_ln50_fu_201_p1;

assign grp_fu_268_p1 = sext_ln50_3_fu_213_p1;

assign grp_get_phase_factor_fu_104_ap_start = grp_get_phase_factor_fu_104_ap_start_reg;

assign grp_get_phase_factor_fu_104_i = select_ln264_fu_149_p3[12:0];

assign i_1_fu_162_p2 = (select_ln264_fu_149_p3 + 14'd1);

assign icmp_ln264_fu_124_p2 = ((indvar_flatten_fu_74 == bound) ? 1'b1 : 1'b0);

assign icmp_ln267_fu_143_p2 = ((i_fu_70 == 14'd8192) ? 1'b1 : 1'b0);

assign mul_ln50_fu_217_p0 = sext_ln50_fu_201_p1;

assign mul_ln50_fu_217_p1 = sext_ln50_1_fu_205_p1;

assign mul_ln51_fu_223_p0 = sext_ln50_2_fu_209_p1;

assign mul_ln51_fu_223_p1 = sext_ln50_1_fu_205_p1;

assign select_ln264_fu_149_p3 = ((icmp_ln267_fu_143_p2[0:0] == 1'b1) ? 14'd0 : i_fu_70);

assign sext_ln50_1_fu_205_p1 = $signed(temp_data1_M_real_fu_173_p4);

assign sext_ln50_2_fu_209_p1 = $signed(grp_get_phase_factor_fu_104_ap_return_1);

assign sext_ln50_3_fu_213_p1 = $signed(temp_data1_M_imag_fu_183_p4);

assign sext_ln50_fu_201_p1 = $signed(grp_get_phase_factor_fu_104_ap_return_0);

assign temp_data1_M_imag_fu_183_p4 = {{fft1_out_dout[63:48]}};

assign temp_data1_M_real_fu_173_p4 = {{fft1_out_dout[47:32]}};

assign trunc_ln1_fu_233_p4 = {{grp_fu_260_p3[31:16]}};

assign trunc_ln274_fu_229_p1 = fft1_out_dout[31:0];

assign trunc_ln275_1_fu_242_p4 = {{grp_fu_268_p3[31:16]}};

assign twiddle_out0_din = trunc_ln274_reg_325_pp0_iter5_reg;

assign twiddle_out1_din = {{trunc_ln275_1_fu_242_p4}, {trunc_ln1_fu_233_p4}};

endmodule //fft_16k_ssr2_i14_c16_t18_top_twiddle_Pipeline_VITIS_LOOP_264_1_VITIS_LOOP_267_2
