-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_16k_ssr2_i14_c16_t18_top_reorder is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    input_stream_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    input_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    input_stream_empty_n : IN STD_LOGIC;
    input_stream_read : OUT STD_LOGIC;
    reorder_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    reorder_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    reorder_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    reorder_out_full_n : IN STD_LOGIC;
    reorder_out_write : OUT STD_LOGIC;
    iter_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    iter_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    iter_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    iter_empty_n : IN STD_LOGIC;
    iter_read : OUT STD_LOGIC;
    iter_c24_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    iter_c24_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    iter_c24_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    iter_c24_full_n : IN STD_LOGIC;
    iter_c24_write : OUT STD_LOGIC );
end;


architecture behav of fft_16k_ssr2_i14_c16_t18_top_reorder is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv45_0 : STD_LOGIC_VECTOR (44 downto 0) := "000000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv45_1 : STD_LOGIC_VECTOR (44 downto 0) := "000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv14_2000 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_1FFE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000001111111111110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal input_stream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln129_reg_736 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp25_reg_758 : STD_LOGIC_VECTOR (0 downto 0);
    signal reorder_out_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln129_reg_736_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal iter_blk_n : STD_LOGIC;
    signal iter_c24_blk_n : STD_LOGIC;
    signal indvar_flatten8_reg_291 : STD_LOGIC_VECTOR (44 downto 0);
    signal j_reg_302 : STD_LOGIC_VECTOR (30 downto 0);
    signal k_reg_313 : STD_LOGIC_VECTOR (13 downto 0);
    signal wr_reg_324 : STD_LOGIC_VECTOR (0 downto 0);
    signal rd_reg_335 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_reg_346 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_reg_357 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_2_reg_368 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_2_reg_379 : STD_LOGIC_VECTOR (31 downto 0);
    signal iter_2_reg_720 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal sub_fu_400_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_726 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_fu_405_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_reg_731 : STD_LOGIC_VECTOR (44 downto 0);
    signal icmp_ln129_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op75_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln129_fu_417_p2 : STD_LOGIC_VECTOR (44 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln135_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln135_reg_745 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln129_3_fu_443_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln129_3_reg_753 : STD_LOGIC_VECTOR (30 downto 0);
    signal cmp25_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln135_1_fu_460_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln135_1_reg_762 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln135_1_reg_762_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1_reg_768 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln135_fu_474_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln129_4_fu_502_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln129_4_reg_778 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln129_5_fu_509_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln129_5_reg_783 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_condition_pp0_exit_iter1_state6 : STD_LOGIC;
    signal buff_0_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_0_0_ce0 : STD_LOGIC;
    signal buff_0_0_we0 : STD_LOGIC;
    signal buff_0_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_0_0_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_0_0_ce1 : STD_LOGIC;
    signal buff_0_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_0_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_0_1_ce0 : STD_LOGIC;
    signal buff_0_1_we0 : STD_LOGIC;
    signal buff_0_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_0_1_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_0_1_ce1 : STD_LOGIC;
    signal buff_0_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_1_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_1_0_ce0 : STD_LOGIC;
    signal buff_1_0_we0 : STD_LOGIC;
    signal buff_1_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_1_0_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_1_0_ce1 : STD_LOGIC;
    signal buff_1_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_1_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_1_1_ce0 : STD_LOGIC;
    signal buff_1_1_we0 : STD_LOGIC;
    signal buff_1_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buff_1_1_address1 : STD_LOGIC_VECTOR (12 downto 0);
    signal buff_1_1_ce1 : STD_LOGIC;
    signal buff_1_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_done : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_idle : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_ready : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_input_stream_read : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_ce0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_we0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_ce0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_we0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_ce0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_we0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_ce0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_we0 : STD_LOGIC;
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_j_phi_fu_306_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_wr_phi_fu_328_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rd_phi_fu_339_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_c_phi_fu_350_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_r_phi_fu_361_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_3_fu_645_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_r_2_reg_368 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln129_2_fu_494_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_3_fu_654_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_c_2_reg_379 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln129_1_fu_486_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln155_fu_549_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln141_fu_573_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln142_fu_597_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal rd_2_fu_120 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal rd_3_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal wr_2_fu_124 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal wr_3_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln133_fu_538_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln135_fu_524_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln141_fu_605_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_2_fu_423_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln129_fu_451_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln129_fu_435_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln135_2_fu_528_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_2_fu_542_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_1_fu_516_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln133_1_fu_557_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln141_fu_567_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln133_fu_532_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal lshr_ln2_fu_581_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln142_fu_591_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln144_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_633_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal c_1_fu_639_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln156_fu_685_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln155_fu_692_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_184 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component fft_16k_ssr2_i14_c16_t18_top_reorder_Pipeline_pipeup_l1_pipeup_l2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_stream_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        input_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        input_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        input_stream_empty_n : IN STD_LOGIC;
        input_stream_read : OUT STD_LOGIC;
        buff_0_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        buff_0_0_ce0 : OUT STD_LOGIC;
        buff_0_0_we0 : OUT STD_LOGIC;
        buff_0_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buff_0_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        buff_0_1_ce0 : OUT STD_LOGIC;
        buff_0_1_we0 : OUT STD_LOGIC;
        buff_0_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buff_1_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        buff_1_0_ce0 : OUT STD_LOGIC;
        buff_1_0_we0 : OUT STD_LOGIC;
        buff_1_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        buff_1_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        buff_1_1_ce0 : OUT STD_LOGIC;
        buff_1_1_we0 : OUT STD_LOGIC;
        buff_1_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component fft_16k_ssr2_i14_c16_t18_top_reorder_buff_0_0_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    buff_0_0_U : component fft_16k_ssr2_i14_c16_t18_top_reorder_buff_0_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buff_0_0_address0,
        ce0 => buff_0_0_ce0,
        we0 => buff_0_0_we0,
        d0 => buff_0_0_d0,
        address1 => buff_0_0_address1,
        ce1 => buff_0_0_ce1,
        q1 => buff_0_0_q1);

    buff_0_1_U : component fft_16k_ssr2_i14_c16_t18_top_reorder_buff_0_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buff_0_1_address0,
        ce0 => buff_0_1_ce0,
        we0 => buff_0_1_we0,
        d0 => buff_0_1_d0,
        address1 => buff_0_1_address1,
        ce1 => buff_0_1_ce1,
        q1 => buff_0_1_q1);

    buff_1_0_U : component fft_16k_ssr2_i14_c16_t18_top_reorder_buff_0_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buff_1_0_address0,
        ce0 => buff_1_0_ce0,
        we0 => buff_1_0_we0,
        d0 => buff_1_0_d0,
        address1 => buff_1_0_address1,
        ce1 => buff_1_0_ce1,
        q1 => buff_1_0_q1);

    buff_1_1_U : component fft_16k_ssr2_i14_c16_t18_top_reorder_buff_0_0_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8192,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buff_1_1_address0,
        ce0 => buff_1_1_ce0,
        we0 => buff_1_1_we0,
        d0 => buff_1_1_d0,
        address1 => buff_1_1_address1,
        ce1 => buff_1_1_ce1,
        q1 => buff_1_1_q1);

    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390 : component fft_16k_ssr2_i14_c16_t18_top_reorder_Pipeline_pipeup_l1_pipeup_l2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start,
        ap_done => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_done,
        ap_idle => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_idle,
        ap_ready => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_ready,
        input_stream_dout => input_stream_dout,
        input_stream_num_data_valid => ap_const_lv3_0,
        input_stream_fifo_cap => ap_const_lv3_0,
        input_stream_empty_n => input_stream_empty_n,
        input_stream_read => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_input_stream_read,
        buff_0_0_address0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_address0,
        buff_0_0_ce0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_ce0,
        buff_0_0_we0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_we0,
        buff_0_0_d0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_d0,
        buff_0_1_address0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_address0,
        buff_0_1_ce0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_ce0,
        buff_0_1_we0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_we0,
        buff_0_1_d0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_d0,
        buff_1_0_address0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_address0,
        buff_1_0_ce0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_ce0,
        buff_1_0_we0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_we0,
        buff_1_0_d0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_d0,
        buff_1_1_address0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_address0,
        buff_1_1_ce0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_ce0,
        buff_1_1_we0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_we0,
        buff_1_1_d0 => grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if (((ap_const_logic_1 = ap_condition_pp0_exit_iter1_state6) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
                        ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state6))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_ready = ap_const_logic_1)) then 
                    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_2_reg_379_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if (((cmp25_reg_758 = ap_const_lv1_0) and (icmp_ln129_reg_736 = ap_const_lv1_0))) then 
                    c_2_reg_379 <= select_ln129_1_fu_486_p3;
                elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0))) then 
                    c_2_reg_379 <= c_3_fu_654_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    c_2_reg_379 <= ap_phi_reg_pp0_iter1_c_2_reg_379;
                end if;
            end if; 
        end if;
    end process;

    c_reg_346_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                c_reg_346 <= c_2_reg_379;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                c_reg_346 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    indvar_flatten8_reg_291_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln129_fu_412_p2 = ap_const_lv1_0))) then 
                indvar_flatten8_reg_291 <= add_ln129_fu_417_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                indvar_flatten8_reg_291 <= ap_const_lv45_0;
            end if; 
        end if;
    end process;

    j_reg_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_reg_302 <= select_ln129_3_reg_753;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                j_reg_302 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    k_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln129_fu_412_p2 = ap_const_lv1_0))) then 
                k_reg_313 <= add_ln135_fu_474_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                k_reg_313 <= ap_const_lv14_0;
            end if; 
        end if;
    end process;

    r_2_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_184)) then
                if (((cmp25_reg_758 = ap_const_lv1_0) and (icmp_ln129_reg_736 = ap_const_lv1_0))) then 
                    r_2_reg_368 <= select_ln129_2_fu_494_p3;
                elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0))) then 
                    r_2_reg_368 <= r_3_fu_645_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    r_2_reg_368 <= ap_phi_reg_pp0_iter1_r_2_reg_368;
                end if;
            end if; 
        end if;
    end process;

    r_reg_357_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                r_reg_357 <= r_2_reg_368;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                r_reg_357 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    rd_reg_335_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                rd_reg_335 <= select_ln129_5_reg_783;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                rd_reg_335 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    wr_reg_324_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                wr_reg_324 <= select_ln129_4_reg_778;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                wr_reg_324 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                cmp25_reg_758 <= cmp25_fu_455_p2;
                icmp_ln129_reg_736 <= icmp_ln129_fu_412_p2;
                icmp_ln129_reg_736_pp0_iter1_reg <= icmp_ln129_reg_736;
                icmp_ln135_reg_745 <= icmp_ln135_fu_429_p2;
                lshr_ln1_reg_768 <= select_ln129_fu_435_p3(12 downto 1);
                trunc_ln135_1_reg_762 <= trunc_ln135_1_fu_460_p1;
                trunc_ln135_1_reg_762_pp0_iter1_reg <= trunc_ln135_1_reg_762;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                iter_2_reg_720 <= iter_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                rd_2_fu_120 <= rd_3_fu_669_p2;
                wr_2_fu_124 <= wr_3_fu_663_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                select_ln129_3_reg_753 <= select_ln129_3_fu_443_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln129_4_reg_778 <= select_ln129_4_fu_502_p3;
                select_ln129_5_reg_783 <= select_ln129_5_fu_509_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sub_reg_726 <= sub_fu_400_p2;
                    tmp_reg_731(44 downto 13) <= tmp_fu_405_p3(44 downto 13);
            end if;
        end if;
    end process;
    tmp_reg_731(12 downto 0) <= "0000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_state1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_condition_pp0_exit_iter1_state6, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state6))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter1_state6)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln129_fu_417_p2 <= std_logic_vector(unsigned(indvar_flatten8_reg_291) + unsigned(ap_const_lv45_1));
    add_ln133_fu_532_p2 <= std_logic_vector(unsigned(trunc_ln135_2_fu_528_p1) + unsigned(ap_const_lv14_1));
    add_ln135_fu_474_p2 <= std_logic_vector(unsigned(select_ln129_fu_435_p3) + unsigned(ap_const_lv14_1));
    add_ln141_fu_567_p2 <= std_logic_vector(unsigned(tmp_1_fu_516_p3) + unsigned(lshr_ln133_1_fu_557_p4));
    add_ln142_fu_591_p2 <= std_logic_vector(unsigned(tmp_1_fu_516_p3) + unsigned(lshr_ln2_fu_581_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_done)
    begin
        if ((grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_pp0_stage0_iter1, ap_block_state7_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_pp0_stage0_iter1, ap_block_state7_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_pp0_stage0_iter1, ap_block_state7_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, iter_empty_n, iter_c24_full_n)
    begin
                ap_block_state1 <= ((iter_c24_full_n = ap_const_logic_0) or (iter_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state6_pp0_stage0_iter1_assign_proc : process(input_stream_empty_n, ap_predicate_op75_read_state6)
    begin
                ap_block_state6_pp0_stage0_iter1 <= ((input_stream_empty_n = ap_const_logic_0) and (ap_predicate_op75_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage0_iter2_assign_proc : process(reorder_out_full_n, icmp_ln129_reg_736_pp0_iter1_reg)
    begin
                ap_block_state7_pp0_stage0_iter2 <= ((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (reorder_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_184_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_184 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_pp0_exit_iter1_state6_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter1_state6 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state6 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln129_fu_412_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln129_fu_412_p2 = ap_const_lv1_1))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_c_phi_fu_350_p4_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln129_reg_736_pp0_iter1_reg, c_reg_346, c_2_reg_379)
    begin
        if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_c_phi_fu_350_p4 <= c_2_reg_379;
        else 
            ap_phi_mux_c_phi_fu_350_p4 <= c_reg_346;
        end if; 
    end process;


    ap_phi_mux_j_phi_fu_306_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, j_reg_302, select_ln129_3_reg_753)
    begin
        if (((icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_j_phi_fu_306_p4 <= select_ln129_3_reg_753;
        else 
            ap_phi_mux_j_phi_fu_306_p4 <= j_reg_302;
        end if; 
    end process;


    ap_phi_mux_r_phi_fu_361_p4_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln129_reg_736_pp0_iter1_reg, r_reg_357, r_2_reg_368)
    begin
        if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_r_phi_fu_361_p4 <= r_2_reg_368;
        else 
            ap_phi_mux_r_phi_fu_361_p4 <= r_reg_357;
        end if; 
    end process;


    ap_phi_mux_rd_phi_fu_339_p4_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln129_reg_736_pp0_iter1_reg, rd_reg_335, select_ln129_5_reg_783)
    begin
        if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_rd_phi_fu_339_p4 <= select_ln129_5_reg_783;
        else 
            ap_phi_mux_rd_phi_fu_339_p4 <= rd_reg_335;
        end if; 
    end process;


    ap_phi_mux_wr_phi_fu_328_p4_assign_proc : process(ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln129_reg_736_pp0_iter1_reg, wr_reg_324, select_ln129_4_reg_778)
    begin
        if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_wr_phi_fu_328_p4 <= select_ln129_4_reg_778;
        else 
            ap_phi_mux_wr_phi_fu_328_p4 <= wr_reg_324;
        end if; 
    end process;

    ap_phi_reg_pp0_iter1_c_2_reg_379 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter1_r_2_reg_368 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op75_read_state6_assign_proc : process(icmp_ln129_reg_736, cmp25_reg_758)
    begin
                ap_predicate_op75_read_state6 <= ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;

    buff_0_0_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_address0, ap_CS_fsm_state3, zext_ln141_fu_573_p1, zext_ln142_fu_597_p1, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_0_address0 <= zext_ln142_fu_597_p1(13 - 1 downto 0);
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_0_address0 <= zext_ln141_fu_573_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_0_address0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_address0;
        else 
            buff_0_0_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    buff_0_0_address1 <= zext_ln155_fu_549_p1(13 - 1 downto 0);

    buff_0_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_ce0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_0_0_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_0_ce0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_ce0;
        else 
            buff_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_0_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_0_ce1 <= ap_const_logic_1;
        else 
            buff_0_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buff_0_0_d0_assign_proc : process(input_stream_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_d0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1, trunc_ln141_fu_605_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_0_d0 <= input_stream_dout(63 downto 32);
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_0_d0 <= trunc_ln141_fu_605_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_0_d0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_d0;
        else 
            buff_0_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buff_0_0_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_we0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_0_0_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_0_we0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_0_we0;
        else 
            buff_0_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_0_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_address0, ap_CS_fsm_state3, zext_ln141_fu_573_p1, zext_ln142_fu_597_p1, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_1_address0 <= zext_ln141_fu_573_p1(13 - 1 downto 0);
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_1_address0 <= zext_ln142_fu_597_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_1_address0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_address0;
        else 
            buff_0_1_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    buff_0_1_address1 <= zext_ln155_fu_549_p1(13 - 1 downto 0);

    buff_0_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_ce0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_0_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_1_ce0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_ce0;
        else 
            buff_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_0_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_1_ce1 <= ap_const_logic_1;
        else 
            buff_0_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buff_0_1_d0_assign_proc : process(input_stream_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_d0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1, trunc_ln141_fu_605_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_1_d0 <= trunc_ln141_fu_605_p1;
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_0_1_d0 <= input_stream_dout(63 downto 32);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_1_d0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_d0;
        else 
            buff_0_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buff_0_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_we0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_0_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_0_1_we0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_0_1_we0;
        else 
            buff_0_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_1_0_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_address0, ap_CS_fsm_state3, zext_ln141_fu_573_p1, zext_ln142_fu_597_p1, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_0_address0 <= zext_ln142_fu_597_p1(13 - 1 downto 0);
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_0_address0 <= zext_ln141_fu_573_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_0_address0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_address0;
        else 
            buff_1_0_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    buff_1_0_address1 <= zext_ln155_fu_549_p1(13 - 1 downto 0);

    buff_1_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_ce0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_1_0_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_0_ce0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_ce0;
        else 
            buff_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_1_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_0_ce1 <= ap_const_logic_1;
        else 
            buff_1_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buff_1_0_d0_assign_proc : process(input_stream_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_d0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1, trunc_ln141_fu_605_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_0_d0 <= input_stream_dout(63 downto 32);
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_0_d0 <= trunc_ln141_fu_605_p1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_0_d0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_d0;
        else 
            buff_1_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buff_1_0_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_we0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_1_0_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_0_we0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_0_we0;
        else 
            buff_1_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_1_1_address0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_address0, ap_CS_fsm_state3, zext_ln141_fu_573_p1, zext_ln142_fu_597_p1, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_1_address0 <= zext_ln141_fu_573_p1(13 - 1 downto 0);
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_1_address0 <= zext_ln142_fu_597_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_1_address0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_address0;
        else 
            buff_1_1_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    buff_1_1_address1 <= zext_ln155_fu_549_p1(13 - 1 downto 0);

    buff_1_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_ce0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_1_1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_1_ce0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_ce0;
        else 
            buff_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_1_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_1_ce1 <= ap_const_logic_1;
        else 
            buff_1_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buff_1_1_d0_assign_proc : process(input_stream_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_d0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1, trunc_ln141_fu_605_p1)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_1_d0 <= trunc_ln141_fu_605_p1;
        elsif (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_1_1_d0 <= input_stream_dout(63 downto 32);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_1_d0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_d0;
        else 
            buff_1_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buff_1_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln129_reg_736, cmp25_reg_758, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_we0, ap_CS_fsm_state3, trunc_ln133_fu_538_p1, trunc_ln135_fu_524_p1)
    begin
        if ((((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_1) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (trunc_ln135_fu_524_p1 = ap_const_lv1_0) and (trunc_ln133_fu_538_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buff_1_1_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            buff_1_1_we0 <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_buff_1_1_we0;
        else 
            buff_1_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    c_1_fu_639_p2 <= std_logic_vector(unsigned(select_ln129_1_fu_486_p3) + unsigned(ap_const_lv32_2));
    c_3_fu_654_p3 <= 
        ap_const_lv32_0 when (icmp_ln144_fu_627_p2(0) = '1') else 
        c_1_fu_639_p2;
    cmp25_fu_455_p2 <= "1" when (signed(zext_ln129_fu_451_p1) < signed(sub_reg_726)) else "0";
    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_ap_start_reg;
    icmp_ln129_fu_412_p2 <= "1" when (indvar_flatten8_reg_291 = tmp_reg_731) else "0";
    icmp_ln135_fu_429_p2 <= "1" when (k_reg_313 = ap_const_lv14_2000) else "0";
    icmp_ln144_fu_627_p2 <= "1" when (select_ln129_1_fu_486_p3 = ap_const_lv32_1FFE) else "0";

    input_stream_blk_n_assign_proc : process(input_stream_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln129_reg_736, cmp25_reg_758)
    begin
        if (((cmp25_reg_758 = ap_const_lv1_1) and (icmp_ln129_reg_736 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            input_stream_blk_n <= input_stream_empty_n;
        else 
            input_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    input_stream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op75_read_state6, ap_block_pp0_stage0_11001, grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_input_stream_read, ap_CS_fsm_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_predicate_op75_read_state6 = ap_const_boolean_1))) then 
            input_stream_read <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_stream_read <= grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_390_input_stream_read;
        else 
            input_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    iter_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, iter_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            iter_blk_n <= iter_empty_n;
        else 
            iter_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    iter_c24_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, iter_c24_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            iter_c24_blk_n <= iter_c24_full_n;
        else 
            iter_c24_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    iter_c24_din <= iter_dout;

    iter_c24_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            iter_c24_write <= ap_const_logic_1;
        else 
            iter_c24_write <= ap_const_logic_0;
        end if; 
    end process;


    iter_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            iter_read <= ap_const_logic_1;
        else 
            iter_read <= ap_const_logic_0;
        end if; 
    end process;

    j_2_fu_423_p2 <= std_logic_vector(unsigned(ap_phi_mux_j_phi_fu_306_p4) + unsigned(ap_const_lv31_1));
    lshr_ln133_1_fu_557_p4 <= select_ln129_1_fu_486_p3(13 downto 1);
    lshr_ln2_fu_581_p4 <= add_ln133_fu_532_p2(13 downto 1);
    r_1_fu_633_p2 <= std_logic_vector(unsigned(select_ln129_2_fu_494_p3) + unsigned(ap_const_lv32_1));
    r_3_fu_645_p3 <= 
        r_1_fu_633_p2 when (icmp_ln144_fu_627_p2(0) = '1') else 
        select_ln129_2_fu_494_p3;
    rd_3_fu_669_p2 <= (select_ln129_5_fu_509_p3 xor ap_const_lv1_1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    reorder_out_blk_n_assign_proc : process(reorder_out_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln129_reg_736_pp0_iter1_reg)
    begin
        if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            reorder_out_blk_n <= reorder_out_full_n;
        else 
            reorder_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    reorder_out_din <= (select_ln156_fu_685_p3 & select_ln155_fu_692_p3);

    reorder_out_write_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln129_reg_736_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln129_reg_736_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            reorder_out_write <= ap_const_logic_1;
        else 
            reorder_out_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln129_1_fu_486_p3 <= 
        ap_const_lv32_0 when (icmp_ln135_reg_745(0) = '1') else 
        ap_phi_mux_c_phi_fu_350_p4;
    select_ln129_2_fu_494_p3 <= 
        ap_const_lv32_0 when (icmp_ln135_reg_745(0) = '1') else 
        ap_phi_mux_r_phi_fu_361_p4;
    select_ln129_3_fu_443_p3 <= 
        j_2_fu_423_p2 when (icmp_ln135_fu_429_p2(0) = '1') else 
        ap_phi_mux_j_phi_fu_306_p4;
    select_ln129_4_fu_502_p3 <= 
        wr_2_fu_124 when (icmp_ln135_reg_745(0) = '1') else 
        ap_phi_mux_wr_phi_fu_328_p4;
    select_ln129_5_fu_509_p3 <= 
        rd_2_fu_120 when (icmp_ln135_reg_745(0) = '1') else 
        ap_phi_mux_rd_phi_fu_339_p4;
    select_ln129_fu_435_p3 <= 
        ap_const_lv14_0 when (icmp_ln135_fu_429_p2(0) = '1') else 
        k_reg_313;
    select_ln155_fu_692_p3 <= 
        buff_0_1_q1 when (trunc_ln135_1_reg_762_pp0_iter1_reg(0) = '1') else 
        buff_0_0_q1;
    select_ln156_fu_685_p3 <= 
        buff_1_1_q1 when (trunc_ln135_1_reg_762_pp0_iter1_reg(0) = '1') else 
        buff_1_0_q1;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_fu_400_p2 <= std_logic_vector(unsigned(iter_2_reg_720) + unsigned(ap_const_lv32_FFFFFFFF));
    tmp_1_fu_516_p3 <= (select_ln129_4_fu_502_p3 & ap_const_lv12_0);
    tmp_2_fu_542_p3 <= (select_ln129_5_fu_509_p3 & lshr_ln1_reg_768);
    tmp_fu_405_p3 <= (iter_2_reg_720 & ap_const_lv13_0);
    trunc_ln133_fu_538_p1 <= select_ln129_2_fu_494_p3(1 - 1 downto 0);
    trunc_ln135_1_fu_460_p1 <= select_ln129_fu_435_p3(1 - 1 downto 0);
    trunc_ln135_2_fu_528_p1 <= select_ln129_1_fu_486_p3(14 - 1 downto 0);
    trunc_ln135_fu_524_p1 <= select_ln129_1_fu_486_p3(1 - 1 downto 0);
    trunc_ln141_fu_605_p1 <= input_stream_dout(32 - 1 downto 0);
    wr_3_fu_663_p2 <= (select_ln129_4_fu_502_p3 xor ap_const_lv1_1);
    zext_ln129_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln129_3_fu_443_p3),32));
    zext_ln141_fu_573_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln141_fu_567_p2),64));
    zext_ln142_fu_597_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln142_fu_591_p2),64));
    zext_ln155_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_542_p3),64));
end behav;
