// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_4k_ssr2_i16_c16_t16_top_radix2p_Pipeline_VITIS_LOOP_172_1_VITIS_LOOP_175_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reorder_out_dout,
        reorder_out_num_data_valid,
        reorder_out_fifo_cap,
        reorder_out_empty_n,
        reorder_out_read,
        fft1_out_din,
        fft1_out_num_data_valid,
        fft1_out_fifo_cap,
        fft1_out_full_n,
        fft1_out_write,
        bound
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] reorder_out_dout;
input  [2:0] reorder_out_num_data_valid;
input  [2:0] reorder_out_fifo_cap;
input   reorder_out_empty_n;
output   reorder_out_read;
output  [63:0] fft1_out_din;
input  [2:0] fft1_out_num_data_valid;
input  [2:0] fft1_out_fifo_cap;
input   fft1_out_full_n;
output   fft1_out_write;
input  [42:0] bound;

reg ap_idle;
reg reorder_out_read;
reg fft1_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln172_fu_91_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    reorder_out_blk_n;
wire    ap_block_pp0_stage0;
reg    fft1_out_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [42:0] indvar_flatten_fu_60;
wire   [42:0] add_ln172_fu_96_p2;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] trunc_ln180_fu_107_p1;
wire   [15:0] trunc_ln180_3_fu_121_p4;
wire  signed [16:0] sext_ln181_1_fu_145_p1;
wire  signed [16:0] sext_ln181_fu_141_p1;
wire   [15:0] trunc_ln180_2_fu_111_p4;
wire   [15:0] trunc_ln180_4_fu_131_p4;
wire  signed [16:0] sext_ln182_1_fu_159_p1;
wire  signed [16:0] sext_ln182_fu_155_p1;
wire   [16:0] a_fu_149_p2;
wire   [16:0] b_fu_163_p2;
wire   [16:0] c_fu_169_p2;
wire   [16:0] d_fu_175_p2;
wire   [15:0] dout_temp_data1_M_imag_fu_211_p4;
wire   [15:0] dout_temp_data1_M_real_fu_201_p4;
wire   [15:0] dout_temp_data0_M_imag_fu_191_p4;
wire   [15:0] dout_temp_data0_M_real_fu_181_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 indvar_flatten_fu_60 = 43'd0;
#0 ap_done_reg = 1'b0;
end

fft_4k_ssr2_i16_c16_t16_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_60 <= 43'd0;
        end else if (((icmp_ln172_fu_91_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_60 <= add_ln172_fu_96_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln172_fu_91_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fft1_out_blk_n = fft1_out_full_n;
    end else begin
        fft1_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        fft1_out_write = 1'b1;
    end else begin
        fft1_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        reorder_out_blk_n = reorder_out_empty_n;
    end else begin
        reorder_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        reorder_out_read = 1'b1;
    end else begin
        reorder_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_149_p2 = ($signed(sext_ln181_1_fu_145_p1) + $signed(sext_ln181_fu_141_p1));

assign add_ln172_fu_96_p2 = (indvar_flatten_fu_60 + 43'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((fft1_out_full_n == 1'b0) | (reorder_out_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign b_fu_163_p2 = ($signed(sext_ln182_1_fu_159_p1) + $signed(sext_ln182_fu_155_p1));

assign c_fu_169_p2 = ($signed(sext_ln181_fu_141_p1) - $signed(sext_ln181_1_fu_145_p1));

assign d_fu_175_p2 = ($signed(sext_ln182_fu_155_p1) - $signed(sext_ln182_1_fu_159_p1));

assign dout_temp_data0_M_imag_fu_191_p4 = {{b_fu_163_p2[16:1]}};

assign dout_temp_data0_M_real_fu_181_p4 = {{a_fu_149_p2[16:1]}};

assign dout_temp_data1_M_imag_fu_211_p4 = {{d_fu_175_p2[16:1]}};

assign dout_temp_data1_M_real_fu_201_p4 = {{c_fu_169_p2[16:1]}};

assign fft1_out_din = {{{{dout_temp_data1_M_imag_fu_211_p4}, {dout_temp_data1_M_real_fu_201_p4}}, {dout_temp_data0_M_imag_fu_191_p4}}, {dout_temp_data0_M_real_fu_181_p4}};

assign icmp_ln172_fu_91_p2 = ((indvar_flatten_fu_60 == bound) ? 1'b1 : 1'b0);

assign sext_ln181_1_fu_145_p1 = $signed(trunc_ln180_3_fu_121_p4);

assign sext_ln181_fu_141_p1 = $signed(trunc_ln180_fu_107_p1);

assign sext_ln182_1_fu_159_p1 = $signed(trunc_ln180_4_fu_131_p4);

assign sext_ln182_fu_155_p1 = $signed(trunc_ln180_2_fu_111_p4);

assign trunc_ln180_2_fu_111_p4 = {{reorder_out_dout[31:16]}};

assign trunc_ln180_3_fu_121_p4 = {{reorder_out_dout[47:32]}};

assign trunc_ln180_4_fu_131_p4 = {{reorder_out_dout[63:48]}};

assign trunc_ln180_fu_107_p1 = reorder_out_dout[15:0];

endmodule //fft_4k_ssr2_i16_c16_t16_top_radix2p_Pipeline_VITIS_LOOP_172_1_VITIS_LOOP_175_2
