// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_4k_ssr2_i16_c16_t16_top_dma_in (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        din,
        input_stream_din,
        input_stream_num_data_valid,
        input_stream_fifo_cap,
        input_stream_full_n,
        input_stream_write,
        iter,
        iter_c25_din,
        iter_c25_num_data_valid,
        iter_c25_fifo_cap,
        iter_c25_full_n,
        iter_c25_write
);

parameter    ap_ST_fsm_state1 = 74'd1;
parameter    ap_ST_fsm_state2 = 74'd2;
parameter    ap_ST_fsm_state3 = 74'd4;
parameter    ap_ST_fsm_state4 = 74'd8;
parameter    ap_ST_fsm_state5 = 74'd16;
parameter    ap_ST_fsm_state6 = 74'd32;
parameter    ap_ST_fsm_state7 = 74'd64;
parameter    ap_ST_fsm_state8 = 74'd128;
parameter    ap_ST_fsm_state9 = 74'd256;
parameter    ap_ST_fsm_state10 = 74'd512;
parameter    ap_ST_fsm_state11 = 74'd1024;
parameter    ap_ST_fsm_state12 = 74'd2048;
parameter    ap_ST_fsm_state13 = 74'd4096;
parameter    ap_ST_fsm_state14 = 74'd8192;
parameter    ap_ST_fsm_state15 = 74'd16384;
parameter    ap_ST_fsm_state16 = 74'd32768;
parameter    ap_ST_fsm_state17 = 74'd65536;
parameter    ap_ST_fsm_state18 = 74'd131072;
parameter    ap_ST_fsm_state19 = 74'd262144;
parameter    ap_ST_fsm_state20 = 74'd524288;
parameter    ap_ST_fsm_state21 = 74'd1048576;
parameter    ap_ST_fsm_state22 = 74'd2097152;
parameter    ap_ST_fsm_state23 = 74'd4194304;
parameter    ap_ST_fsm_state24 = 74'd8388608;
parameter    ap_ST_fsm_state25 = 74'd16777216;
parameter    ap_ST_fsm_state26 = 74'd33554432;
parameter    ap_ST_fsm_state27 = 74'd67108864;
parameter    ap_ST_fsm_state28 = 74'd134217728;
parameter    ap_ST_fsm_state29 = 74'd268435456;
parameter    ap_ST_fsm_state30 = 74'd536870912;
parameter    ap_ST_fsm_state31 = 74'd1073741824;
parameter    ap_ST_fsm_state32 = 74'd2147483648;
parameter    ap_ST_fsm_state33 = 74'd4294967296;
parameter    ap_ST_fsm_state34 = 74'd8589934592;
parameter    ap_ST_fsm_state35 = 74'd17179869184;
parameter    ap_ST_fsm_state36 = 74'd34359738368;
parameter    ap_ST_fsm_state37 = 74'd68719476736;
parameter    ap_ST_fsm_state38 = 74'd137438953472;
parameter    ap_ST_fsm_state39 = 74'd274877906944;
parameter    ap_ST_fsm_state40 = 74'd549755813888;
parameter    ap_ST_fsm_state41 = 74'd1099511627776;
parameter    ap_ST_fsm_state42 = 74'd2199023255552;
parameter    ap_ST_fsm_state43 = 74'd4398046511104;
parameter    ap_ST_fsm_state44 = 74'd8796093022208;
parameter    ap_ST_fsm_state45 = 74'd17592186044416;
parameter    ap_ST_fsm_state46 = 74'd35184372088832;
parameter    ap_ST_fsm_state47 = 74'd70368744177664;
parameter    ap_ST_fsm_state48 = 74'd140737488355328;
parameter    ap_ST_fsm_state49 = 74'd281474976710656;
parameter    ap_ST_fsm_state50 = 74'd562949953421312;
parameter    ap_ST_fsm_state51 = 74'd1125899906842624;
parameter    ap_ST_fsm_state52 = 74'd2251799813685248;
parameter    ap_ST_fsm_state53 = 74'd4503599627370496;
parameter    ap_ST_fsm_state54 = 74'd9007199254740992;
parameter    ap_ST_fsm_state55 = 74'd18014398509481984;
parameter    ap_ST_fsm_state56 = 74'd36028797018963968;
parameter    ap_ST_fsm_state57 = 74'd72057594037927936;
parameter    ap_ST_fsm_state58 = 74'd144115188075855872;
parameter    ap_ST_fsm_state59 = 74'd288230376151711744;
parameter    ap_ST_fsm_state60 = 74'd576460752303423488;
parameter    ap_ST_fsm_state61 = 74'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 74'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 74'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 74'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 74'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 74'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 74'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 74'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 74'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 74'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 74'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 74'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 74'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 74'd9444732965739290427392;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [63:0] m_axi_gmem1_WDATA;
output  [7:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [63:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] din;
output  [63:0] input_stream_din;
input  [2:0] input_stream_num_data_valid;
input  [2:0] input_stream_fifo_cap;
input   input_stream_full_n;
output   input_stream_write;
input  [31:0] iter;
output  [31:0] iter_c25_din;
input  [2:0] iter_c25_num_data_valid;
input  [2:0] iter_c25_fifo_cap;
input   iter_c25_full_n;
output   iter_c25_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem1_ARVALID;
reg[63:0] m_axi_gmem1_ARADDR;
reg[0:0] m_axi_gmem1_ARID;
reg[31:0] m_axi_gmem1_ARLEN;
reg[2:0] m_axi_gmem1_ARSIZE;
reg[1:0] m_axi_gmem1_ARBURST;
reg[1:0] m_axi_gmem1_ARLOCK;
reg[3:0] m_axi_gmem1_ARCACHE;
reg[2:0] m_axi_gmem1_ARPROT;
reg[3:0] m_axi_gmem1_ARQOS;
reg[3:0] m_axi_gmem1_ARREGION;
reg[0:0] m_axi_gmem1_ARUSER;
reg m_axi_gmem1_RREADY;
reg input_stream_write;
reg iter_c25_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [73:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    gmem1_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    iter_c25_blk_n;
wire   [19:0] iter_6_fu_112_p1;
reg   [19:0] iter_6_reg_175;
reg    ap_block_state1;
wire   [29:0] empty_fu_134_p3;
reg   [29:0] empty_reg_180;
wire  signed [60:0] trunc_ln61_1_fu_142_p4;
reg   [60:0] trunc_ln61_1_reg_185;
wire   [31:0] zext_ln61_fu_163_p1;
wire   [30:0] tmp_4_fu_167_p3;
reg   [30:0] tmp_4_reg_200;
wire    ap_CS_fsm_state73;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_idle;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_ready;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWVALID;
wire   [63:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWADDR;
wire   [0:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWID;
wire   [31:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWLEN;
wire   [2:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWBURST;
wire   [1:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWPROT;
wire   [3:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWQOS;
wire   [3:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWREGION;
wire   [0:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWUSER;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WVALID;
wire   [63:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WDATA;
wire   [7:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WSTRB;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WLAST;
wire   [0:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WID;
wire   [0:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WUSER;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARVALID;
wire   [63:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARADDR;
wire   [0:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARID;
wire   [31:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARLEN;
wire   [2:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARBURST;
wire   [1:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARPROT;
wire   [3:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARQOS;
wire   [3:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARREGION;
wire   [0:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARUSER;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_RREADY;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_BREADY;
wire   [63:0] grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_input_stream_din;
wire    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_input_stream_write;
reg    grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start_reg;
wire    ap_CS_fsm_state74;
wire  signed [63:0] sext_ln61_fu_152_p1;
wire   [18:0] trunc_ln61_fu_116_p1;
wire   [0:0] icmp_ln61_fu_128_p2;
wire   [29:0] trunc_ln_fu_120_p3;
reg   [73:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 74'd1;
#0 grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start_reg = 1'b0;
end

fft_4k_ssr2_i16_c16_t16_top_dma_in_Pipeline_VITIS_LOOP_61_1 grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start),
    .ap_done(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done),
    .ap_idle(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_idle),
    .ap_ready(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_ready),
    .m_axi_gmem1_AWVALID(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .input_stream_din(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_input_stream_din),
    .input_stream_num_data_valid(3'd0),
    .input_stream_fifo_cap(3'd0),
    .input_stream_full_n(input_stream_full_n),
    .input_stream_write(grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_input_stream_write),
    .tmp_4(tmp_4_reg_200),
    .sext_ln61(trunc_ln61_1_reg_185)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state73)) begin
            grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start_reg <= 1'b1;
        end else if ((grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_ready == 1'b1)) begin
            grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_reg_180[29 : 11] <= empty_fu_134_p3[29 : 11];
        iter_6_reg_175 <= iter_6_fu_112_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        tmp_4_reg_200[30 : 11] <= tmp_4_fu_167_p3[30 : 11];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem1_ARREADY == 1'b1))) begin
        trunc_ln61_1_reg_185 <= {{din[63:3]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem1_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

always @ (*) begin
    if ((grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done == 1'b0)) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gmem1_blk_n_AR = m_axi_gmem1_ARREADY;
    end else begin
        gmem1_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        input_stream_write = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_input_stream_write;
    end else begin
        input_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_c25_blk_n = iter_c25_full_n;
    end else begin
        iter_c25_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        iter_c25_write = 1'b1;
    end else begin
        iter_c25_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem1_ARREADY == 1'b1))) begin
        m_axi_gmem1_ARADDR = sext_ln61_fu_152_p1;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARADDR = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARADDR;
    end else begin
        m_axi_gmem1_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARBURST = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARBURST;
    end else begin
        m_axi_gmem1_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARCACHE = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARCACHE;
    end else begin
        m_axi_gmem1_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARID = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARID;
    end else begin
        m_axi_gmem1_ARID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem1_ARREADY == 1'b1))) begin
        m_axi_gmem1_ARLEN = zext_ln61_fu_163_p1;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARLEN = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARLEN;
    end else begin
        m_axi_gmem1_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARLOCK = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARLOCK;
    end else begin
        m_axi_gmem1_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARPROT = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARPROT;
    end else begin
        m_axi_gmem1_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARQOS = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARQOS;
    end else begin
        m_axi_gmem1_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARREGION = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARREGION;
    end else begin
        m_axi_gmem1_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARSIZE = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARSIZE;
    end else begin
        m_axi_gmem1_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARUSER = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARUSER;
    end else begin
        m_axi_gmem1_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem1_ARREADY == 1'b1))) begin
        m_axi_gmem1_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_ARVALID = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_ARVALID;
    end else begin
        m_axi_gmem1_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        m_axi_gmem1_RREADY = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_m_axi_gmem1_RREADY;
    end else begin
        m_axi_gmem1_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (m_axi_gmem1_ARREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            if (((grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (iter_c25_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign empty_fu_134_p3 = ((icmp_ln61_fu_128_p2[0:0] == 1'b1) ? trunc_ln_fu_120_p3 : 30'd0);

assign grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_ap_start_reg;

assign icmp_ln61_fu_128_p2 = (($signed(iter_6_fu_112_p1) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign input_stream_din = grp_dma_in_Pipeline_VITIS_LOOP_61_1_fu_102_input_stream_din;

assign iter_6_fu_112_p1 = iter[19:0];

assign iter_c25_din = iter;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_WDATA = 64'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 8'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign sext_ln61_fu_152_p1 = trunc_ln61_1_fu_142_p4;

assign start_out = real_start;

assign tmp_4_fu_167_p3 = {{iter_6_reg_175}, {11'd0}};

assign trunc_ln61_1_fu_142_p4 = {{din[63:3]}};

assign trunc_ln61_fu_116_p1 = iter[18:0];

assign trunc_ln_fu_120_p3 = {{trunc_ln61_fu_116_p1}, {11'd0}};

assign zext_ln61_fu_163_p1 = empty_reg_180;

always @ (posedge ap_clk) begin
    empty_reg_180[10:0] <= 11'b00000000000;
    tmp_4_reg_200[10:0] <= 11'b00000000000;
end

endmodule //fft_4k_ssr2_i16_c16_t16_top_dma_in
