

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76"},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.entry_proc_U0"},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dma_in_U0"},
	{"ID" : "4", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dma_in_U0.grp_dma_in_Pipeline_VITIS_LOOP_53_1_fu_98"},
	{"ID" : "5", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dma_in_U0.grp_dma_in_Pipeline_VITIS_LOOP_53_1_fu_98.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0"},
	{"ID" : "7", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.entry_proc42_U0"},
	{"ID" : "8", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0"},
	{"ID" : "9", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0"},
	{"ID" : "10", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.Block_newFuncRoot_proc_proc_U0"},
	{"ID" : "11", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.Block_newFuncRoot_proc_proc5_U0"},
	{"ID" : "12", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.fft_fft_params_U0"},
	{"ID" : "13", "Level" : "6", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.fft_fft_params_U0.fft_syn_fft_params_U0"},
	{"ID" : "14", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.Block_newFuncRoot_proc_proc6_U0"},
	{"ID" : "15", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.empty_U"},
	{"ID" : "16", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.fft_config_U"},
	{"ID" : "17", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.fft_status_U"},
	{"ID" : "18", "Level" : "5", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.fft_serial_kernel_U0.dataflow_in_loop_VITIS_LOOP_158_1_U0.start_for_Block_newFuncRoot_proc_proc6_U0_U"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_serial_kernel_wrapper_U0.p_channel_U"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dma_out_U0"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dma_out_U0.grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101"},
	{"ID" : "22", "Level" : "4", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dma_out_U0.grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.dout_c_U"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.input_stream_U"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.iter_c10_U"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.fft_out_U"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.iter_c_U"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.start_for_dma_out_U0_U"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fft_core_fu_76.start_for_fft_serial_kernel_wrapper_U0_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U"}]}
set DependenceCheckSize 0
