-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_4k_ssr2_i16_c16_t16_top_twiddle_Pipeline_VITIS_LOOP_264_1_VITIS_LOOP_267_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fft1_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    fft1_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    fft1_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    fft1_out_empty_n : IN STD_LOGIC;
    fft1_out_read : OUT STD_LOGIC;
    twiddle_out0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    twiddle_out0_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    twiddle_out0_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    twiddle_out0_full_n : IN STD_LOGIC;
    twiddle_out0_write : OUT STD_LOGIC;
    twiddle_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    twiddle_out1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    twiddle_out1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    twiddle_out1_full_n : IN STD_LOGIC;
    twiddle_out1_write : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (42 downto 0) );
end;


architecture behav of fft_4k_ssr2_i16_c16_t16_top_twiddle_Pipeline_VITIS_LOOP_264_1_VITIS_LOOP_267_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv43_0 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000000";
    constant ap_const_lv43_1 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000001";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln264_fu_126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal fft1_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal twiddle_out0_blk_n : STD_LOGIC;
    signal twiddle_out1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln264_reg_297 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln50_fu_203_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln50_2_fu_211_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln50_3_fu_215_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln50_fu_219_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln50_reg_317 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln50_reg_317_pp0_iter4_reg : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln51_fu_225_p2 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln51_reg_322 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln51_reg_322_pp0_iter4_reg : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln274_fu_231_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln274_reg_327 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln274_reg_327_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln274_reg_327_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_get_phase_factor_fu_106_ap_start : STD_LOGIC;
    signal grp_get_phase_factor_fu_106_ap_done : STD_LOGIC;
    signal grp_get_phase_factor_fu_106_ap_idle : STD_LOGIC;
    signal grp_get_phase_factor_fu_106_ap_ready : STD_LOGIC;
    signal grp_get_phase_factor_fu_106_ap_ce : STD_LOGIC;
    signal grp_get_phase_factor_fu_106_i : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_get_phase_factor_fu_106_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_get_phase_factor_fu_106_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state4_pp0_stage0_iter3_ignore_call10 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6_ignore_call10 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp27 : BOOLEAN;
    signal grp_get_phase_factor_fu_106_ap_start_reg : STD_LOGIC := '0';
    signal i_fu_72 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal i_1_fu_164_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal indvar_flatten_fu_76 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000000";
    signal add_ln264_fu_131_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln267_fu_145_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln264_fu_151_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal temp_data1_M_real_fu_175_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal temp_data1_M_imag_fu_185_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln50_fu_219_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln50_fu_219_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln50_1_fu_207_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal mul_ln51_fu_225_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln51_fu_225_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_262_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_270_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln275_1_fu_244_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_fu_235_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_262_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_262_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_270_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_270_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_262_ce : STD_LOGIC;
    signal grp_fu_270_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_4k_ssr2_i16_c16_t16_top_get_phase_factor IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        i : IN STD_LOGIC_VECTOR (10 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_4k_ssr2_i16_c16_t16_top_mul_16s_16s_30_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component fft_4k_ssr2_i16_c16_t16_top_mac_mulsub_16s_16s_30s_30_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component fft_4k_ssr2_i16_c16_t16_top_mac_muladd_16s_16s_30s_30_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component fft_4k_ssr2_i16_c16_t16_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    grp_get_phase_factor_fu_106 : component fft_4k_ssr2_i16_c16_t16_top_get_phase_factor
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_get_phase_factor_fu_106_ap_start,
        ap_done => grp_get_phase_factor_fu_106_ap_done,
        ap_idle => grp_get_phase_factor_fu_106_ap_idle,
        ap_ready => grp_get_phase_factor_fu_106_ap_ready,
        ap_ce => grp_get_phase_factor_fu_106_ap_ce,
        i => grp_get_phase_factor_fu_106_i,
        ap_return_0 => grp_get_phase_factor_fu_106_ap_return_0,
        ap_return_1 => grp_get_phase_factor_fu_106_ap_return_1);

    mul_16s_16s_30_1_1_U31 : component fft_4k_ssr2_i16_c16_t16_top_mul_16s_16s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln50_fu_219_p0,
        din1 => mul_ln50_fu_219_p1,
        dout => mul_ln50_fu_219_p2);

    mul_16s_16s_30_1_1_U32 : component fft_4k_ssr2_i16_c16_t16_top_mul_16s_16s_30_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 30)
    port map (
        din0 => mul_ln51_fu_225_p0,
        din1 => mul_ln51_fu_225_p1,
        dout => mul_ln51_fu_225_p2);

    mac_mulsub_16s_16s_30s_30_4_1_U33 : component fft_4k_ssr2_i16_c16_t16_top_mac_mulsub_16s_16s_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_262_p0,
        din1 => grp_fu_262_p1,
        din2 => mul_ln50_reg_317_pp0_iter4_reg,
        ce => grp_fu_262_ce,
        dout => grp_fu_262_p3);

    mac_muladd_16s_16s_30s_30_4_1_U34 : component fft_4k_ssr2_i16_c16_t16_top_mac_muladd_16s_16s_30s_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 30,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_270_p0,
        din1 => grp_fu_270_p1,
        din2 => mul_ln51_reg_322_pp0_iter4_reg,
        ce => grp_fu_270_ce,
        dout => grp_fu_270_p3);

    flow_control_loop_pipe_sequential_init_U : component fft_4k_ssr2_i16_c16_t16_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    grp_get_phase_factor_fu_106_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_get_phase_factor_fu_106_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln264_fu_126_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    grp_get_phase_factor_fu_106_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_get_phase_factor_fu_106_ap_ready = ap_const_logic_1)) then 
                    grp_get_phase_factor_fu_106_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_72 <= ap_const_lv12_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    i_fu_72 <= i_1_fu_164_p2;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_76 <= ap_const_lv43_0;
                elsif (((icmp_ln264_fu_126_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_76 <= add_ln264_fu_131_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln264_reg_297 <= icmp_ln264_fu_126_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                mul_ln50_reg_317 <= mul_ln50_fu_219_p2;
                mul_ln50_reg_317_pp0_iter4_reg <= mul_ln50_reg_317;
                mul_ln51_reg_322 <= mul_ln51_fu_225_p2;
                mul_ln51_reg_322_pp0_iter4_reg <= mul_ln51_reg_322;
                trunc_ln274_reg_327 <= trunc_ln274_fu_231_p1;
                trunc_ln274_reg_327_pp0_iter4_reg <= trunc_ln274_reg_327;
                trunc_ln274_reg_327_pp0_iter5_reg <= trunc_ln274_reg_327_pp0_iter4_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln264_fu_131_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_76) + unsigned(ap_const_lv43_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_block_state4_pp0_stage0_iter3, ap_block_state7_pp0_stage0_iter6)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_block_state4_pp0_stage0_iter3, ap_block_state7_pp0_stage0_iter6)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp27_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_block_state4_pp0_stage0_iter3_ignore_call10, ap_block_state7_pp0_stage0_iter6_ignore_call10)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp27 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_ignore_call10)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3_ignore_call10)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, ap_block_state4_pp0_stage0_iter3, ap_block_state7_pp0_stage0_iter6)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter3)));
    end process;


    ap_block_state4_pp0_stage0_iter3_assign_proc : process(fft1_out_empty_n)
    begin
                ap_block_state4_pp0_stage0_iter3 <= (fft1_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state4_pp0_stage0_iter3_ignore_call10_assign_proc : process(fft1_out_empty_n)
    begin
                ap_block_state4_pp0_stage0_iter3_ignore_call10 <= (fft1_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state7_pp0_stage0_iter6_assign_proc : process(twiddle_out0_full_n, twiddle_out1_full_n)
    begin
                ap_block_state7_pp0_stage0_iter6 <= ((twiddle_out1_full_n = ap_const_logic_0) or (twiddle_out0_full_n = ap_const_logic_0));
    end process;


    ap_block_state7_pp0_stage0_iter6_ignore_call10_assign_proc : process(twiddle_out0_full_n, twiddle_out1_full_n)
    begin
                ap_block_state7_pp0_stage0_iter6_ignore_call10 <= ((twiddle_out1_full_n = ap_const_logic_0) or (twiddle_out0_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln264_fu_126_p2)
    begin
        if (((icmp_ln264_fu_126_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    fft1_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter3, fft1_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            fft1_out_blk_n <= fft1_out_empty_n;
        else 
            fft1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    fft1_out_read_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            fft1_out_read <= ap_const_logic_1;
        else 
            fft1_out_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_262_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_262_ce <= ap_const_logic_1;
        else 
            grp_fu_262_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_262_p0 <= sext_ln50_2_fu_211_p1(16 - 1 downto 0);
    grp_fu_262_p1 <= sext_ln50_3_fu_215_p1(16 - 1 downto 0);

    grp_fu_270_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_270_ce <= ap_const_logic_1;
        else 
            grp_fu_270_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_270_p0 <= sext_ln50_fu_203_p1(16 - 1 downto 0);
    grp_fu_270_p1 <= sext_ln50_3_fu_215_p1(16 - 1 downto 0);

    grp_get_phase_factor_fu_106_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp27)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp27) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_get_phase_factor_fu_106_ap_ce <= ap_const_logic_1;
        else 
            grp_get_phase_factor_fu_106_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_get_phase_factor_fu_106_ap_start <= grp_get_phase_factor_fu_106_ap_start_reg;
    grp_get_phase_factor_fu_106_i <= select_ln264_fu_151_p3(11 - 1 downto 0);
    i_1_fu_164_p2 <= std_logic_vector(unsigned(select_ln264_fu_151_p3) + unsigned(ap_const_lv12_1));
    icmp_ln264_fu_126_p2 <= "1" when (indvar_flatten_fu_76 = bound) else "0";
    icmp_ln267_fu_145_p2 <= "1" when (i_fu_72 = ap_const_lv12_800) else "0";
    mul_ln50_fu_219_p0 <= sext_ln50_fu_203_p1(16 - 1 downto 0);
    mul_ln50_fu_219_p1 <= sext_ln50_1_fu_207_p1(16 - 1 downto 0);
    mul_ln51_fu_225_p0 <= sext_ln50_2_fu_211_p1(16 - 1 downto 0);
    mul_ln51_fu_225_p1 <= sext_ln50_1_fu_207_p1(16 - 1 downto 0);
    select_ln264_fu_151_p3 <= 
        ap_const_lv12_0 when (icmp_ln267_fu_145_p2(0) = '1') else 
        i_fu_72;
        sext_ln50_1_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(temp_data1_M_real_fu_175_p4),30));

        sext_ln50_2_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_get_phase_factor_fu_106_ap_return_1),30));

        sext_ln50_3_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(temp_data1_M_imag_fu_185_p4),30));

        sext_ln50_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_get_phase_factor_fu_106_ap_return_0),30));

    temp_data1_M_imag_fu_185_p4 <= fft1_out_dout(63 downto 48);
    temp_data1_M_real_fu_175_p4 <= fft1_out_dout(47 downto 32);
    trunc_ln1_fu_235_p4 <= grp_fu_262_p3(29 downto 14);
    trunc_ln274_fu_231_p1 <= fft1_out_dout(32 - 1 downto 0);
    trunc_ln275_1_fu_244_p4 <= grp_fu_270_p3(29 downto 14);

    twiddle_out0_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, twiddle_out0_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            twiddle_out0_blk_n <= twiddle_out0_full_n;
        else 
            twiddle_out0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    twiddle_out0_din <= trunc_ln274_reg_327_pp0_iter5_reg;

    twiddle_out0_write_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            twiddle_out0_write <= ap_const_logic_1;
        else 
            twiddle_out0_write <= ap_const_logic_0;
        end if; 
    end process;


    twiddle_out1_blk_n_assign_proc : process(ap_enable_reg_pp0_iter6, twiddle_out1_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            twiddle_out1_blk_n <= twiddle_out1_full_n;
        else 
            twiddle_out1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    twiddle_out1_din <= (trunc_ln275_1_fu_244_p4 & trunc_ln1_fu_235_p4);

    twiddle_out1_write_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            twiddle_out1_write <= ap_const_logic_1;
        else 
            twiddle_out1_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
