// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_4k_ssr2_i16_c16_t16_top_reorder (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_stream_dout,
        input_stream_num_data_valid,
        input_stream_fifo_cap,
        input_stream_empty_n,
        input_stream_read,
        reorder_out_din,
        reorder_out_num_data_valid,
        reorder_out_fifo_cap,
        reorder_out_full_n,
        reorder_out_write,
        iter_dout,
        iter_num_data_valid,
        iter_fifo_cap,
        iter_empty_n,
        iter_read,
        iter_c24_din,
        iter_c24_num_data_valid,
        iter_c24_fifo_cap,
        iter_c24_full_n,
        iter_c24_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state8 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [63:0] input_stream_dout;
input  [2:0] input_stream_num_data_valid;
input  [2:0] input_stream_fifo_cap;
input   input_stream_empty_n;
output   input_stream_read;
output  [63:0] reorder_out_din;
input  [2:0] reorder_out_num_data_valid;
input  [2:0] reorder_out_fifo_cap;
input   reorder_out_full_n;
output   reorder_out_write;
input  [31:0] iter_dout;
input  [2:0] iter_num_data_valid;
input  [2:0] iter_fifo_cap;
input   iter_empty_n;
output   iter_read;
output  [31:0] iter_c24_din;
input  [2:0] iter_c24_num_data_valid;
input  [2:0] iter_c24_fifo_cap;
input   iter_c24_full_n;
output   iter_c24_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg input_stream_read;
reg reorder_out_write;
reg iter_read;
reg iter_c24_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_stream_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln129_reg_738;
reg   [0:0] cmp25_reg_760;
reg    reorder_out_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln129_reg_738_pp0_iter1_reg;
reg    iter_blk_n;
reg    iter_c24_blk_n;
reg   [42:0] indvar_flatten8_reg_293;
reg   [30:0] j_reg_304;
reg   [11:0] k_reg_315;
reg   [0:0] wr_reg_326;
reg   [0:0] rd_reg_337;
reg   [31:0] c_reg_348;
reg   [31:0] r_reg_359;
reg   [31:0] r_2_reg_370;
reg   [31:0] c_2_reg_381;
reg   [31:0] iter_2_reg_722;
reg    ap_block_state1;
wire   [31:0] sub_fu_402_p2;
reg   [31:0] sub_reg_728;
wire    ap_CS_fsm_state4;
wire   [42:0] tmp_fu_407_p3;
reg   [42:0] tmp_reg_733;
wire   [0:0] icmp_ln129_fu_414_p2;
reg    ap_predicate_op75_read_state6;
reg    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_state7_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [42:0] add_ln129_fu_419_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln135_fu_431_p2;
reg   [0:0] icmp_ln135_reg_747;
wire   [30:0] select_ln129_3_fu_445_p3;
reg   [30:0] select_ln129_3_reg_755;
wire   [0:0] cmp25_fu_457_p2;
wire   [0:0] trunc_ln135_1_fu_462_p1;
reg   [0:0] trunc_ln135_1_reg_764;
reg   [0:0] trunc_ln135_1_reg_764_pp0_iter1_reg;
reg   [9:0] lshr_ln1_reg_770;
wire   [11:0] add_ln135_fu_476_p2;
wire   [0:0] select_ln129_4_fu_504_p3;
reg   [0:0] select_ln129_4_reg_780;
wire   [0:0] select_ln129_5_fu_511_p3;
reg   [0:0] select_ln129_5_reg_785;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter1_state6;
reg   [10:0] buff_0_0_address0;
reg    buff_0_0_ce0;
reg    buff_0_0_we0;
reg   [31:0] buff_0_0_d0;
wire   [10:0] buff_0_0_address1;
reg    buff_0_0_ce1;
wire   [31:0] buff_0_0_q1;
reg   [10:0] buff_0_1_address0;
reg    buff_0_1_ce0;
reg    buff_0_1_we0;
reg   [31:0] buff_0_1_d0;
wire   [10:0] buff_0_1_address1;
reg    buff_0_1_ce1;
wire   [31:0] buff_0_1_q1;
reg   [10:0] buff_1_0_address0;
reg    buff_1_0_ce0;
reg    buff_1_0_we0;
reg   [31:0] buff_1_0_d0;
wire   [10:0] buff_1_0_address1;
reg    buff_1_0_ce1;
wire   [31:0] buff_1_0_q1;
reg   [10:0] buff_1_1_address0;
reg    buff_1_1_ce0;
reg    buff_1_1_we0;
reg   [31:0] buff_1_1_d0;
wire   [10:0] buff_1_1_address1;
reg    buff_1_1_ce1;
wire   [31:0] buff_1_1_q1;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_done;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_idle;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_ready;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_input_stream_read;
wire   [10:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_address0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_ce0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_we0;
wire   [31:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_d0;
wire   [10:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_address0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_ce0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_we0;
wire   [31:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_d0;
wire   [10:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_address0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_ce0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_we0;
wire   [31:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_d0;
wire   [10:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_address0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_ce0;
wire    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_we0;
wire   [31:0] grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_d0;
reg   [30:0] ap_phi_mux_j_phi_fu_308_p4;
reg   [0:0] ap_phi_mux_wr_phi_fu_330_p4;
reg   [0:0] ap_phi_mux_rd_phi_fu_341_p4;
reg   [31:0] ap_phi_mux_c_phi_fu_352_p4;
reg   [31:0] ap_phi_mux_r_phi_fu_363_p4;
wire   [31:0] r_3_fu_647_p3;
wire   [31:0] ap_phi_reg_pp0_iter1_r_2_reg_370;
wire   [31:0] select_ln129_2_fu_496_p3;
wire   [31:0] c_3_fu_656_p3;
wire   [31:0] ap_phi_reg_pp0_iter1_c_2_reg_381;
wire   [31:0] select_ln129_1_fu_488_p3;
reg    grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln155_fu_551_p1;
wire   [63:0] zext_ln141_fu_575_p1;
wire   [63:0] zext_ln142_fu_599_p1;
reg   [0:0] rd_2_fu_122;
wire   [0:0] rd_3_fu_671_p2;
reg   [0:0] wr_2_fu_126;
wire   [0:0] wr_3_fu_665_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] trunc_ln133_fu_540_p1;
wire   [0:0] trunc_ln135_fu_526_p1;
wire   [31:0] trunc_ln141_fu_607_p1;
wire   [30:0] j_2_fu_425_p2;
wire   [31:0] zext_ln129_fu_453_p1;
wire   [11:0] select_ln129_fu_437_p3;
wire   [11:0] trunc_ln135_2_fu_530_p1;
wire   [10:0] tmp_2_fu_544_p3;
wire   [10:0] tmp_1_fu_518_p3;
wire   [10:0] lshr_ln133_1_fu_559_p4;
wire   [10:0] add_ln141_fu_569_p2;
wire   [11:0] add_ln133_fu_534_p2;
wire   [10:0] lshr_ln2_fu_583_p4;
wire   [10:0] add_ln142_fu_593_p2;
wire   [0:0] icmp_ln144_fu_629_p2;
wire   [31:0] r_1_fu_635_p2;
wire   [31:0] c_1_fu_641_p2;
wire   [31:0] select_ln156_fu_687_p3;
wire   [31:0] select_ln155_fu_694_p3;
wire    ap_CS_fsm_state8;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_184;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start_reg = 1'b0;
#0 rd_2_fu_122 = 1'd0;
#0 wr_2_fu_126 = 1'd0;
end

fft_4k_ssr2_i16_c16_t16_top_reorder_buff_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
buff_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buff_0_0_address0),
    .ce0(buff_0_0_ce0),
    .we0(buff_0_0_we0),
    .d0(buff_0_0_d0),
    .address1(buff_0_0_address1),
    .ce1(buff_0_0_ce1),
    .q1(buff_0_0_q1)
);

fft_4k_ssr2_i16_c16_t16_top_reorder_buff_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
buff_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buff_0_1_address0),
    .ce0(buff_0_1_ce0),
    .we0(buff_0_1_we0),
    .d0(buff_0_1_d0),
    .address1(buff_0_1_address1),
    .ce1(buff_0_1_ce1),
    .q1(buff_0_1_q1)
);

fft_4k_ssr2_i16_c16_t16_top_reorder_buff_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
buff_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buff_1_0_address0),
    .ce0(buff_1_0_ce0),
    .we0(buff_1_0_we0),
    .d0(buff_1_0_d0),
    .address1(buff_1_0_address1),
    .ce1(buff_1_0_ce1),
    .q1(buff_1_0_q1)
);

fft_4k_ssr2_i16_c16_t16_top_reorder_buff_0_0_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
buff_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buff_1_1_address0),
    .ce0(buff_1_1_ce0),
    .we0(buff_1_1_we0),
    .d0(buff_1_1_d0),
    .address1(buff_1_1_address1),
    .ce1(buff_1_1_ce1),
    .q1(buff_1_1_q1)
);

fft_4k_ssr2_i16_c16_t16_top_reorder_Pipeline_pipeup_l1_pipeup_l2 grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start),
    .ap_done(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_done),
    .ap_idle(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_idle),
    .ap_ready(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_ready),
    .input_stream_dout(input_stream_dout),
    .input_stream_num_data_valid(3'd0),
    .input_stream_fifo_cap(3'd0),
    .input_stream_empty_n(input_stream_empty_n),
    .input_stream_read(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_input_stream_read),
    .buff_0_0_address0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_address0),
    .buff_0_0_ce0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_ce0),
    .buff_0_0_we0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_we0),
    .buff_0_0_d0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_d0),
    .buff_0_1_address0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_address0),
    .buff_0_1_ce0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_ce0),
    .buff_0_1_we0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_we0),
    .buff_0_1_d0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_d0),
    .buff_1_0_address0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_address0),
    .buff_1_0_ce0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_ce0),
    .buff_1_0_we0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_we0),
    .buff_1_0_d0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_d0),
    .buff_1_1_address0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_address0),
    .buff_1_1_ce0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_ce0),
    .buff_1_1_we0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_we0),
    .buff_1_1_d0(grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if (((1'b1 == ap_condition_pp0_exit_iter1_state6) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_enable_reg_pp0_iter1 <= 1'b0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state6))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start_reg <= 1'b1;
        end else if ((grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_ready == 1'b1)) begin
            grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if (((cmp25_reg_760 == 1'd0) & (icmp_ln129_reg_738 == 1'd0))) begin
            c_2_reg_381 <= select_ln129_1_fu_488_p3;
        end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0))) begin
            c_2_reg_381 <= c_3_fu_656_p3;
        end else if ((1'b1 == 1'b1)) begin
            c_2_reg_381 <= ap_phi_reg_pp0_iter1_c_2_reg_381;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        c_reg_348 <= c_2_reg_381;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        c_reg_348 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln129_fu_414_p2 == 1'd0))) begin
        indvar_flatten8_reg_293 <= add_ln129_fu_419_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        indvar_flatten8_reg_293 <= 43'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_reg_304 <= select_ln129_3_reg_755;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        j_reg_304 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln129_fu_414_p2 == 1'd0))) begin
        k_reg_315 <= add_ln135_fu_476_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        k_reg_315 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_184)) begin
        if (((cmp25_reg_760 == 1'd0) & (icmp_ln129_reg_738 == 1'd0))) begin
            r_2_reg_370 <= select_ln129_2_fu_496_p3;
        end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0))) begin
            r_2_reg_370 <= r_3_fu_647_p3;
        end else if ((1'b1 == 1'b1)) begin
            r_2_reg_370 <= ap_phi_reg_pp0_iter1_r_2_reg_370;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_reg_359 <= r_2_reg_370;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        r_reg_359 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        rd_reg_337 <= select_ln129_5_reg_785;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        rd_reg_337 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        wr_reg_326 <= select_ln129_4_reg_780;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        wr_reg_326 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cmp25_reg_760 <= cmp25_fu_457_p2;
        icmp_ln129_reg_738 <= icmp_ln129_fu_414_p2;
        icmp_ln129_reg_738_pp0_iter1_reg <= icmp_ln129_reg_738;
        icmp_ln135_reg_747 <= icmp_ln135_fu_431_p2;
        lshr_ln1_reg_770 <= {{select_ln129_fu_437_p3[10:1]}};
        trunc_ln135_1_reg_764 <= trunc_ln135_1_fu_462_p1;
        trunc_ln135_1_reg_764_pp0_iter1_reg <= trunc_ln135_1_reg_764;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_2_reg_722 <= iter_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        rd_2_fu_122 <= rd_3_fu_671_p2;
        wr_2_fu_126 <= wr_3_fu_665_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        select_ln129_3_reg_755 <= select_ln129_3_fu_445_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln129_4_reg_780 <= select_ln129_4_fu_504_p3;
        select_ln129_5_reg_785 <= select_ln129_5_fu_511_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sub_reg_728 <= sub_fu_402_p2;
        tmp_reg_733[42 : 11] <= tmp_fu_407_p3[42 : 11];
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state6 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln129_fu_414_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_c_phi_fu_352_p4 = c_2_reg_381;
    end else begin
        ap_phi_mux_c_phi_fu_352_p4 = c_reg_348;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_j_phi_fu_308_p4 = select_ln129_3_reg_755;
    end else begin
        ap_phi_mux_j_phi_fu_308_p4 = j_reg_304;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_r_phi_fu_363_p4 = r_2_reg_370;
    end else begin
        ap_phi_mux_r_phi_fu_363_p4 = r_reg_359;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_rd_phi_fu_341_p4 = select_ln129_5_reg_785;
    end else begin
        ap_phi_mux_rd_phi_fu_341_p4 = rd_reg_337;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_wr_phi_fu_330_p4 = select_ln129_4_reg_780;
    end else begin
        ap_phi_mux_wr_phi_fu_330_p4 = wr_reg_326;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_0_address0 = zext_ln142_fu_599_p1;
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_0_address0 = zext_ln141_fu_575_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_0_address0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_address0;
    end else begin
        buff_0_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_0_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_0_ce0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_ce0;
    end else begin
        buff_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_0_ce1 = 1'b1;
    end else begin
        buff_0_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_0_d0 = {{input_stream_dout[63:32]}};
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_0_d0 = trunc_ln141_fu_607_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_0_d0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_d0;
    end else begin
        buff_0_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_0_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_0_we0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_0_we0;
    end else begin
        buff_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_1_address0 = zext_ln141_fu_575_p1;
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_1_address0 = zext_ln142_fu_599_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_1_address0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_address0;
    end else begin
        buff_0_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_0_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_1_ce0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_ce0;
    end else begin
        buff_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_1_ce1 = 1'b1;
    end else begin
        buff_0_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_1_d0 = trunc_ln141_fu_607_p1;
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_1_d0 = {{input_stream_dout[63:32]}};
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_1_d0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_d0;
    end else begin
        buff_0_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_0_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_0_1_we0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_0_1_we0;
    end else begin
        buff_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_0_address0 = zext_ln142_fu_599_p1;
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_0_address0 = zext_ln141_fu_575_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_0_address0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_address0;
    end else begin
        buff_1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_1_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_0_ce0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_ce0;
    end else begin
        buff_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_0_ce1 = 1'b1;
    end else begin
        buff_1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_0_d0 = {{input_stream_dout[63:32]}};
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_0_d0 = trunc_ln141_fu_607_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_0_d0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_d0;
    end else begin
        buff_1_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_1_0_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_0_we0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_0_we0;
    end else begin
        buff_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_1_address0 = zext_ln141_fu_575_p1;
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_1_address0 = zext_ln142_fu_599_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_1_address0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_address0;
    end else begin
        buff_1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_1_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_1_ce0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_ce0;
    end else begin
        buff_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_1_ce1 = 1'b1;
    end else begin
        buff_1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_1_d0 = trunc_ln141_fu_607_p1;
    end else if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_1_d0 = {{input_stream_dout[63:32]}};
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_1_d0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_d0;
    end else begin
        buff_1_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd1) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln135_fu_526_p1 == 1'd0) & (trunc_ln133_fu_540_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buff_1_1_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buff_1_1_we0 = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_buff_1_1_we0;
    end else begin
        buff_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_blk_n = input_stream_empty_n;
    end else begin
        input_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op75_read_state6 == 1'b1))) begin
        input_stream_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_stream_read = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_input_stream_read;
    end else begin
        input_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_blk_n = iter_empty_n;
    end else begin
        iter_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_c24_blk_n = iter_c24_full_n;
    end else begin
        iter_c24_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_c24_write = 1'b1;
    end else begin
        iter_c24_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_read = 1'b1;
    end else begin
        iter_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        reorder_out_blk_n = reorder_out_full_n;
    end else begin
        reorder_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        reorder_out_write = 1'b1;
    end else begin
        reorder_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state6)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state6)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln129_fu_419_p2 = (indvar_flatten8_reg_293 + 43'd1);

assign add_ln133_fu_534_p2 = (trunc_ln135_2_fu_530_p1 + 12'd1);

assign add_ln135_fu_476_p2 = (select_ln129_fu_437_p3 + 12'd1);

assign add_ln141_fu_569_p2 = (tmp_1_fu_518_p3 + lshr_ln133_1_fu_559_p4);

assign add_ln142_fu_593_p2 = (tmp_1_fu_518_p3 + lshr_ln2_fu_583_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state1 = ((iter_c24_full_n == 1'b0) | (iter_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = ((input_stream_empty_n == 1'b0) & (ap_predicate_op75_read_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter2 = ((icmp_ln129_reg_738_pp0_iter1_reg == 1'd0) & (reorder_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_184 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter1_c_2_reg_381 = 'bx;

assign ap_phi_reg_pp0_iter1_r_2_reg_370 = 'bx;

always @ (*) begin
    ap_predicate_op75_read_state6 = ((cmp25_reg_760 == 1'd1) & (icmp_ln129_reg_738 == 1'd0));
end

assign ap_ready = internal_ap_ready;

assign buff_0_0_address1 = zext_ln155_fu_551_p1;

assign buff_0_1_address1 = zext_ln155_fu_551_p1;

assign buff_1_0_address1 = zext_ln155_fu_551_p1;

assign buff_1_1_address1 = zext_ln155_fu_551_p1;

assign c_1_fu_641_p2 = (select_ln129_1_fu_488_p3 + 32'd2);

assign c_3_fu_656_p3 = ((icmp_ln144_fu_629_p2[0:0] == 1'b1) ? 32'd0 : c_1_fu_641_p2);

assign cmp25_fu_457_p2 = (($signed(zext_ln129_fu_453_p1) < $signed(sub_reg_728)) ? 1'b1 : 1'b0);

assign grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start = grp_reorder_Pipeline_pipeup_l1_pipeup_l2_fu_392_ap_start_reg;

assign icmp_ln129_fu_414_p2 = ((indvar_flatten8_reg_293 == tmp_reg_733) ? 1'b1 : 1'b0);

assign icmp_ln135_fu_431_p2 = ((k_reg_315 == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_629_p2 = ((select_ln129_1_fu_488_p3 == 32'd2046) ? 1'b1 : 1'b0);

assign iter_c24_din = iter_dout;

assign j_2_fu_425_p2 = (ap_phi_mux_j_phi_fu_308_p4 + 31'd1);

assign lshr_ln133_1_fu_559_p4 = {{select_ln129_1_fu_488_p3[11:1]}};

assign lshr_ln2_fu_583_p4 = {{add_ln133_fu_534_p2[11:1]}};

assign r_1_fu_635_p2 = (select_ln129_2_fu_496_p3 + 32'd1);

assign r_3_fu_647_p3 = ((icmp_ln144_fu_629_p2[0:0] == 1'b1) ? r_1_fu_635_p2 : select_ln129_2_fu_496_p3);

assign rd_3_fu_671_p2 = (select_ln129_5_fu_511_p3 ^ 1'd1);

assign reorder_out_din = {{select_ln156_fu_687_p3}, {select_ln155_fu_694_p3}};

assign select_ln129_1_fu_488_p3 = ((icmp_ln135_reg_747[0:0] == 1'b1) ? 32'd0 : ap_phi_mux_c_phi_fu_352_p4);

assign select_ln129_2_fu_496_p3 = ((icmp_ln135_reg_747[0:0] == 1'b1) ? 32'd0 : ap_phi_mux_r_phi_fu_363_p4);

assign select_ln129_3_fu_445_p3 = ((icmp_ln135_fu_431_p2[0:0] == 1'b1) ? j_2_fu_425_p2 : ap_phi_mux_j_phi_fu_308_p4);

assign select_ln129_4_fu_504_p3 = ((icmp_ln135_reg_747[0:0] == 1'b1) ? wr_2_fu_126 : ap_phi_mux_wr_phi_fu_330_p4);

assign select_ln129_5_fu_511_p3 = ((icmp_ln135_reg_747[0:0] == 1'b1) ? rd_2_fu_122 : ap_phi_mux_rd_phi_fu_341_p4);

assign select_ln129_fu_437_p3 = ((icmp_ln135_fu_431_p2[0:0] == 1'b1) ? 12'd0 : k_reg_315);

assign select_ln155_fu_694_p3 = ((trunc_ln135_1_reg_764_pp0_iter1_reg[0:0] == 1'b1) ? buff_0_1_q1 : buff_0_0_q1);

assign select_ln156_fu_687_p3 = ((trunc_ln135_1_reg_764_pp0_iter1_reg[0:0] == 1'b1) ? buff_1_1_q1 : buff_1_0_q1);

assign start_out = real_start;

assign sub_fu_402_p2 = ($signed(iter_2_reg_722) + $signed(32'd4294967295));

assign tmp_1_fu_518_p3 = {{select_ln129_4_fu_504_p3}, {10'd0}};

assign tmp_2_fu_544_p3 = {{select_ln129_5_fu_511_p3}, {lshr_ln1_reg_770}};

assign tmp_fu_407_p3 = {{iter_2_reg_722}, {11'd0}};

assign trunc_ln133_fu_540_p1 = select_ln129_2_fu_496_p3[0:0];

assign trunc_ln135_1_fu_462_p1 = select_ln129_fu_437_p3[0:0];

assign trunc_ln135_2_fu_530_p1 = select_ln129_1_fu_488_p3[11:0];

assign trunc_ln135_fu_526_p1 = select_ln129_1_fu_488_p3[0:0];

assign trunc_ln141_fu_607_p1 = input_stream_dout[31:0];

assign wr_3_fu_665_p2 = (select_ln129_4_fu_504_p3 ^ 1'd1);

assign zext_ln129_fu_453_p1 = select_ln129_3_fu_445_p3;

assign zext_ln141_fu_575_p1 = add_ln141_fu_569_p2;

assign zext_ln142_fu_599_p1 = add_ln142_fu_593_p2;

assign zext_ln155_fu_551_p1 = tmp_2_fu_544_p3;

always @ (posedge ap_clk) begin
    tmp_reg_733[10:0] <= 11'b00000000000;
end

endmodule //fft_4k_ssr2_i16_c16_t16_top_reorder
