// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_4k_ssr2_i16_c16_t16_top_reorder_Pipeline_pipeup_l1_pipeup_l2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_stream_dout,
        input_stream_num_data_valid,
        input_stream_fifo_cap,
        input_stream_empty_n,
        input_stream_read,
        buff_0_0_address0,
        buff_0_0_ce0,
        buff_0_0_we0,
        buff_0_0_d0,
        buff_0_1_address0,
        buff_0_1_ce0,
        buff_0_1_we0,
        buff_0_1_d0,
        buff_1_0_address0,
        buff_1_0_ce0,
        buff_1_0_we0,
        buff_1_0_d0,
        buff_1_1_address0,
        buff_1_1_ce0,
        buff_1_1_we0,
        buff_1_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] input_stream_dout;
input  [2:0] input_stream_num_data_valid;
input  [2:0] input_stream_fifo_cap;
input   input_stream_empty_n;
output   input_stream_read;
output  [10:0] buff_0_0_address0;
output   buff_0_0_ce0;
output   buff_0_0_we0;
output  [31:0] buff_0_0_d0;
output  [10:0] buff_0_1_address0;
output   buff_0_1_ce0;
output   buff_0_1_we0;
output  [31:0] buff_0_1_d0;
output  [10:0] buff_1_0_address0;
output   buff_1_0_ce0;
output   buff_1_0_we0;
output  [31:0] buff_1_0_d0;
output  [10:0] buff_1_1_address0;
output   buff_1_1_ce0;
output   buff_1_1_we0;
output  [31:0] buff_1_1_d0;

reg ap_idle;
reg input_stream_read;
reg buff_0_0_ce0;
reg buff_0_0_we0;
reg buff_0_1_ce0;
reg buff_0_1_we0;
reg buff_1_0_ce0;
reg buff_1_0_we0;
reg buff_1_1_ce0;
reg buff_1_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln119_fu_150_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    input_stream_blk_n;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln121_fu_217_p1;
reg   [11:0] k_fu_62;
wire   [11:0] add_ln121_fu_243_p2;
reg    ap_block_pp0_stage0_11001;
wire    ap_loop_init;
reg   [1:0] i_fu_66;
wire   [1:0] select_ln119_1_fu_195_p3;
reg   [11:0] indvar_flatten_fu_70;
wire   [11:0] add_ln119_1_fu_156_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] trunc_ln119_fu_203_p1;
wire   [31:0] trunc_ln124_fu_225_p1;
wire   [0:0] tmp_fu_179_p3;
wire   [1:0] add_ln119_fu_173_p2;
wire   [11:0] select_ln119_fu_187_p3;
wire   [9:0] lshr_ln_fu_207_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_62 = 12'd0;
#0 i_fu_66 = 2'd0;
#0 indvar_flatten_fu_70 = 12'd0;
#0 ap_done_reg = 1'b0;
end

fft_4k_ssr2_i16_c16_t16_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 2'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_66 <= select_ln119_1_fu_195_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln119_fu_150_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_70 <= add_ln119_1_fu_156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_70 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_62 <= 12'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            k_fu_62 <= add_ln121_fu_243_p2;
        end
    end
end

always @ (*) begin
    if (((icmp_ln119_fu_150_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_0_ce0 = 1'b1;
    end else begin
        buff_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln119_fu_203_p1 == 1'd0))) begin
        buff_0_0_we0 = 1'b1;
    end else begin
        buff_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_0_1_ce0 = 1'b1;
    end else begin
        buff_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln119_fu_203_p1 == 1'd0))) begin
        buff_0_1_we0 = 1'b1;
    end else begin
        buff_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_0_ce0 = 1'b1;
    end else begin
        buff_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln119_fu_203_p1 == 1'd1))) begin
        buff_1_0_we0 = 1'b1;
    end else begin
        buff_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buff_1_1_ce0 = 1'b1;
    end else begin
        buff_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln119_fu_203_p1 == 1'd1))) begin
        buff_1_1_we0 = 1'b1;
    end else begin
        buff_1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_blk_n = input_stream_empty_n;
    end else begin
        input_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_stream_read = 1'b1;
    end else begin
        input_stream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln119_1_fu_156_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln119_fu_173_p2 = (i_fu_66 + 2'd1);

assign add_ln121_fu_243_p2 = (select_ln119_fu_187_p3 + 12'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (input_stream_empty_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign buff_0_0_address0 = zext_ln121_fu_217_p1;

assign buff_0_0_d0 = trunc_ln124_fu_225_p1;

assign buff_0_1_address0 = zext_ln121_fu_217_p1;

assign buff_0_1_d0 = {{input_stream_dout[63:32]}};

assign buff_1_0_address0 = zext_ln121_fu_217_p1;

assign buff_1_0_d0 = trunc_ln124_fu_225_p1;

assign buff_1_1_address0 = zext_ln121_fu_217_p1;

assign buff_1_1_d0 = {{input_stream_dout[63:32]}};

assign icmp_ln119_fu_150_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2048) ? 1'b1 : 1'b0);

assign lshr_ln_fu_207_p4 = {{select_ln119_fu_187_p3[10:1]}};

assign select_ln119_1_fu_195_p3 = ((tmp_fu_179_p3[0:0] == 1'b1) ? add_ln119_fu_173_p2 : i_fu_66);

assign select_ln119_fu_187_p3 = ((tmp_fu_179_p3[0:0] == 1'b1) ? 12'd0 : k_fu_62);

assign tmp_fu_179_p3 = k_fu_62[32'd11];

assign trunc_ln119_fu_203_p1 = select_ln119_1_fu_195_p3[0:0];

assign trunc_ln124_fu_225_p1 = input_stream_dout[31:0];

assign zext_ln121_fu_217_p1 = lshr_ln_fu_207_p4;

endmodule //fft_4k_ssr2_i16_c16_t16_top_reorder_Pipeline_pipeup_l1_pipeup_l2
