// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_16k_ssr2_i14_c16_t18_top_fft_core (
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        din,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        dout,
        iter,
        ap_clk,
        ap_rst,
        dout_ap_vld,
        ap_start,
        din_ap_vld,
        iter_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [63:0] m_axi_gmem1_WDATA;
output  [7:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [63:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] din;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [63:0] m_axi_gmem2_WDATA;
output  [7:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [63:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [8:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] dout;
input  [31:0] iter;
input   ap_clk;
input   ap_rst;
input   dout_ap_vld;
input   ap_start;
input   din_ap_vld;
input   iter_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_dout_c_din;
wire    entry_proc_U0_dout_c_write;
wire    dma_in_U0_ap_start;
wire    dma_in_U0_ap_done;
wire    dma_in_U0_ap_continue;
wire    dma_in_U0_ap_idle;
wire    dma_in_U0_ap_ready;
wire    dma_in_U0_start_out;
wire    dma_in_U0_start_write;
wire    dma_in_U0_m_axi_gmem1_AWVALID;
wire   [63:0] dma_in_U0_m_axi_gmem1_AWADDR;
wire   [0:0] dma_in_U0_m_axi_gmem1_AWID;
wire   [31:0] dma_in_U0_m_axi_gmem1_AWLEN;
wire   [2:0] dma_in_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] dma_in_U0_m_axi_gmem1_AWBURST;
wire   [1:0] dma_in_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] dma_in_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] dma_in_U0_m_axi_gmem1_AWPROT;
wire   [3:0] dma_in_U0_m_axi_gmem1_AWQOS;
wire   [3:0] dma_in_U0_m_axi_gmem1_AWREGION;
wire   [0:0] dma_in_U0_m_axi_gmem1_AWUSER;
wire    dma_in_U0_m_axi_gmem1_WVALID;
wire   [63:0] dma_in_U0_m_axi_gmem1_WDATA;
wire   [7:0] dma_in_U0_m_axi_gmem1_WSTRB;
wire    dma_in_U0_m_axi_gmem1_WLAST;
wire   [0:0] dma_in_U0_m_axi_gmem1_WID;
wire   [0:0] dma_in_U0_m_axi_gmem1_WUSER;
wire    dma_in_U0_m_axi_gmem1_ARVALID;
wire   [63:0] dma_in_U0_m_axi_gmem1_ARADDR;
wire   [0:0] dma_in_U0_m_axi_gmem1_ARID;
wire   [31:0] dma_in_U0_m_axi_gmem1_ARLEN;
wire   [2:0] dma_in_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] dma_in_U0_m_axi_gmem1_ARBURST;
wire   [1:0] dma_in_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] dma_in_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] dma_in_U0_m_axi_gmem1_ARPROT;
wire   [3:0] dma_in_U0_m_axi_gmem1_ARQOS;
wire   [3:0] dma_in_U0_m_axi_gmem1_ARREGION;
wire   [0:0] dma_in_U0_m_axi_gmem1_ARUSER;
wire    dma_in_U0_m_axi_gmem1_RREADY;
wire    dma_in_U0_m_axi_gmem1_BREADY;
wire   [63:0] dma_in_U0_input_stream_din;
wire    dma_in_U0_input_stream_write;
wire   [31:0] dma_in_U0_iter_c25_din;
wire    dma_in_U0_iter_c25_write;
wire    reorder_U0_ap_start;
wire    reorder_U0_ap_done;
wire    reorder_U0_ap_continue;
wire    reorder_U0_ap_idle;
wire    reorder_U0_ap_ready;
wire    reorder_U0_start_out;
wire    reorder_U0_start_write;
wire    reorder_U0_input_stream_read;
wire   [63:0] reorder_U0_reorder_out_din;
wire    reorder_U0_reorder_out_write;
wire    reorder_U0_iter_read;
wire   [31:0] reorder_U0_iter_c24_din;
wire    reorder_U0_iter_c24_write;
wire    radix2p_U0_ap_start;
wire    radix2p_U0_ap_done;
wire    radix2p_U0_ap_continue;
wire    radix2p_U0_ap_idle;
wire    radix2p_U0_ap_ready;
wire    radix2p_U0_start_out;
wire    radix2p_U0_start_write;
wire    radix2p_U0_reorder_out_read;
wire   [63:0] radix2p_U0_fft1_out_din;
wire    radix2p_U0_fft1_out_write;
wire    radix2p_U0_iter_read;
wire   [31:0] radix2p_U0_iter_c23_din;
wire    radix2p_U0_iter_c23_write;
wire    twiddle_U0_ap_start;
wire    twiddle_U0_start_full_n;
wire    twiddle_U0_ap_done;
wire    twiddle_U0_ap_continue;
wire    twiddle_U0_ap_idle;
wire    twiddle_U0_ap_ready;
wire    twiddle_U0_start_out;
wire    twiddle_U0_start_write;
wire    twiddle_U0_fft1_out_read;
wire   [31:0] twiddle_U0_twiddle_out0_din;
wire    twiddle_U0_twiddle_out0_write;
wire   [31:0] twiddle_U0_twiddle_out1_din;
wire    twiddle_U0_twiddle_out1_write;
wire    twiddle_U0_iter_read;
wire   [31:0] twiddle_U0_iter_c21_din;
wire    twiddle_U0_iter_c21_write;
wire   [31:0] twiddle_U0_iter_c22_din;
wire    twiddle_U0_iter_c22_write;
wire    fft_serial_kernel_1_wrapper_U0_ap_start;
wire    fft_serial_kernel_1_wrapper_U0_start_out;
wire    fft_serial_kernel_1_wrapper_U0_start_write;
wire    fft_serial_kernel_1_wrapper_U0_twiddle_out0_read;
wire   [31:0] fft_serial_kernel_1_wrapper_U0_fft2_out0_din;
wire    fft_serial_kernel_1_wrapper_U0_fft2_out0_write;
wire    fft_serial_kernel_1_wrapper_U0_iter_read;
wire   [31:0] fft_serial_kernel_1_wrapper_U0_iter_c20_din;
wire    fft_serial_kernel_1_wrapper_U0_iter_c20_write;
wire    fft_serial_kernel_1_wrapper_U0_ap_done;
wire    fft_serial_kernel_1_wrapper_U0_ap_ready;
wire    fft_serial_kernel_1_wrapper_U0_ap_idle;
wire    fft_serial_kernel_1_wrapper_U0_ap_continue;
wire    fft_serial_kernel_wrapper_U0_twiddle_out1_read;
wire   [31:0] fft_serial_kernel_wrapper_U0_fft2_out1_din;
wire    fft_serial_kernel_wrapper_U0_fft2_out1_write;
wire    fft_serial_kernel_wrapper_U0_iter_read;
wire    fft_serial_kernel_wrapper_U0_ap_start;
wire    fft_serial_kernel_wrapper_U0_ap_done;
wire    fft_serial_kernel_wrapper_U0_ap_ready;
wire    fft_serial_kernel_wrapper_U0_ap_idle;
wire    fft_serial_kernel_wrapper_U0_ap_continue;
wire    joiner_U0_ap_start;
wire    joiner_U0_ap_done;
wire    joiner_U0_ap_continue;
wire    joiner_U0_ap_idle;
wire    joiner_U0_ap_ready;
wire    joiner_U0_fft2_out0_read;
wire    joiner_U0_fft2_out1_read;
wire   [63:0] joiner_U0_joiner_out_din;
wire    joiner_U0_joiner_out_write;
wire    joiner_U0_iter_read;
wire   [17:0] joiner_U0_iter_c_din;
wire    joiner_U0_iter_c_write;
wire    dma_out_U0_ap_start;
wire    dma_out_U0_ap_done;
wire    dma_out_U0_ap_continue;
wire    dma_out_U0_ap_idle;
wire    dma_out_U0_ap_ready;
wire    dma_out_U0_joiner_out_read;
wire    dma_out_U0_m_axi_gmem2_AWVALID;
wire   [63:0] dma_out_U0_m_axi_gmem2_AWADDR;
wire   [0:0] dma_out_U0_m_axi_gmem2_AWID;
wire   [31:0] dma_out_U0_m_axi_gmem2_AWLEN;
wire   [2:0] dma_out_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] dma_out_U0_m_axi_gmem2_AWBURST;
wire   [1:0] dma_out_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] dma_out_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] dma_out_U0_m_axi_gmem2_AWPROT;
wire   [3:0] dma_out_U0_m_axi_gmem2_AWQOS;
wire   [3:0] dma_out_U0_m_axi_gmem2_AWREGION;
wire   [0:0] dma_out_U0_m_axi_gmem2_AWUSER;
wire    dma_out_U0_m_axi_gmem2_WVALID;
wire   [63:0] dma_out_U0_m_axi_gmem2_WDATA;
wire   [7:0] dma_out_U0_m_axi_gmem2_WSTRB;
wire    dma_out_U0_m_axi_gmem2_WLAST;
wire   [0:0] dma_out_U0_m_axi_gmem2_WID;
wire   [0:0] dma_out_U0_m_axi_gmem2_WUSER;
wire    dma_out_U0_m_axi_gmem2_ARVALID;
wire   [63:0] dma_out_U0_m_axi_gmem2_ARADDR;
wire   [0:0] dma_out_U0_m_axi_gmem2_ARID;
wire   [31:0] dma_out_U0_m_axi_gmem2_ARLEN;
wire   [2:0] dma_out_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] dma_out_U0_m_axi_gmem2_ARBURST;
wire   [1:0] dma_out_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] dma_out_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] dma_out_U0_m_axi_gmem2_ARPROT;
wire   [3:0] dma_out_U0_m_axi_gmem2_ARQOS;
wire   [3:0] dma_out_U0_m_axi_gmem2_ARREGION;
wire   [0:0] dma_out_U0_m_axi_gmem2_ARUSER;
wire    dma_out_U0_m_axi_gmem2_RREADY;
wire    dma_out_U0_m_axi_gmem2_BREADY;
wire    dma_out_U0_dout_read;
wire    dma_out_U0_iter_read;
wire    dout_c_full_n;
wire   [63:0] dout_c_dout;
wire   [3:0] dout_c_num_data_valid;
wire   [3:0] dout_c_fifo_cap;
wire    dout_c_empty_n;
wire    input_stream_full_n;
wire   [63:0] input_stream_dout;
wire   [2:0] input_stream_num_data_valid;
wire   [2:0] input_stream_fifo_cap;
wire    input_stream_empty_n;
wire    iter_c25_full_n;
wire   [31:0] iter_c25_dout;
wire   [2:0] iter_c25_num_data_valid;
wire   [2:0] iter_c25_fifo_cap;
wire    iter_c25_empty_n;
wire    reorder_out_full_n;
wire   [63:0] reorder_out_dout;
wire   [2:0] reorder_out_num_data_valid;
wire   [2:0] reorder_out_fifo_cap;
wire    reorder_out_empty_n;
wire    iter_c24_full_n;
wire   [31:0] iter_c24_dout;
wire   [2:0] iter_c24_num_data_valid;
wire   [2:0] iter_c24_fifo_cap;
wire    iter_c24_empty_n;
wire    fft1_out_full_n;
wire   [63:0] fft1_out_dout;
wire   [2:0] fft1_out_num_data_valid;
wire   [2:0] fft1_out_fifo_cap;
wire    fft1_out_empty_n;
wire    iter_c23_full_n;
wire   [31:0] iter_c23_dout;
wire   [2:0] iter_c23_num_data_valid;
wire   [2:0] iter_c23_fifo_cap;
wire    iter_c23_empty_n;
wire    twiddle_out0_full_n;
wire   [31:0] twiddle_out0_dout;
wire   [2:0] twiddle_out0_num_data_valid;
wire   [2:0] twiddle_out0_fifo_cap;
wire    twiddle_out0_empty_n;
wire    twiddle_out1_full_n;
wire   [31:0] twiddle_out1_dout;
wire   [2:0] twiddle_out1_num_data_valid;
wire   [2:0] twiddle_out1_fifo_cap;
wire    twiddle_out1_empty_n;
wire    iter_c21_full_n;
wire   [31:0] iter_c21_dout;
wire   [2:0] iter_c21_num_data_valid;
wire   [2:0] iter_c21_fifo_cap;
wire    iter_c21_empty_n;
wire    iter_c22_full_n;
wire   [31:0] iter_c22_dout;
wire   [2:0] iter_c22_num_data_valid;
wire   [2:0] iter_c22_fifo_cap;
wire    iter_c22_empty_n;
wire    fft2_out0_full_n;
wire   [31:0] fft2_out0_dout;
wire   [2:0] fft2_out0_num_data_valid;
wire   [2:0] fft2_out0_fifo_cap;
wire    fft2_out0_empty_n;
wire    iter_c20_full_n;
wire   [31:0] iter_c20_dout;
wire   [2:0] iter_c20_num_data_valid;
wire   [2:0] iter_c20_fifo_cap;
wire    iter_c20_empty_n;
wire    fft2_out1_full_n;
wire   [31:0] fft2_out1_dout;
wire   [2:0] fft2_out1_num_data_valid;
wire   [2:0] fft2_out1_fifo_cap;
wire    fft2_out1_empty_n;
wire    joiner_out_full_n;
wire   [63:0] joiner_out_dout;
wire   [2:0] joiner_out_num_data_valid;
wire   [2:0] joiner_out_fifo_cap;
wire    joiner_out_empty_n;
wire    iter_c_full_n;
wire   [17:0] iter_c_dout;
wire   [2:0] iter_c_num_data_valid;
wire   [2:0] iter_c_fifo_cap;
wire    iter_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_dma_in_U0_ap_ready;
wire    ap_sync_dma_in_U0_ap_ready;
wire   [0:0] start_for_dma_out_U0_din;
wire    start_for_dma_out_U0_full_n;
wire   [0:0] start_for_dma_out_U0_dout;
wire    start_for_dma_out_U0_empty_n;
wire   [0:0] start_for_reorder_U0_din;
wire    start_for_reorder_U0_full_n;
wire   [0:0] start_for_reorder_U0_dout;
wire    start_for_reorder_U0_empty_n;
wire   [0:0] start_for_radix2p_U0_din;
wire    start_for_radix2p_U0_full_n;
wire   [0:0] start_for_radix2p_U0_dout;
wire    start_for_radix2p_U0_empty_n;
wire   [0:0] start_for_twiddle_U0_din;
wire    start_for_twiddle_U0_full_n;
wire   [0:0] start_for_twiddle_U0_dout;
wire    start_for_twiddle_U0_empty_n;
wire   [0:0] start_for_fft_serial_kernel_1_wrapper_U0_din;
wire    start_for_fft_serial_kernel_1_wrapper_U0_full_n;
wire   [0:0] start_for_fft_serial_kernel_1_wrapper_U0_dout;
wire    start_for_fft_serial_kernel_1_wrapper_U0_empty_n;
wire   [0:0] start_for_fft_serial_kernel_wrapper_U0_din;
wire    start_for_fft_serial_kernel_wrapper_U0_full_n;
wire   [0:0] start_for_fft_serial_kernel_wrapper_U0_dout;
wire    start_for_fft_serial_kernel_wrapper_U0_empty_n;
wire   [0:0] start_for_joiner_U0_din;
wire    start_for_joiner_U0_full_n;
wire   [0:0] start_for_joiner_U0_dout;
wire    start_for_joiner_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_dma_in_U0_ap_ready = 1'b0;
end

fft_16k_ssr2_i14_c16_t18_top_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_dma_out_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .dout(dout),
    .dout_c_din(entry_proc_U0_dout_c_din),
    .dout_c_num_data_valid(dout_c_num_data_valid),
    .dout_c_fifo_cap(dout_c_fifo_cap),
    .dout_c_full_n(dout_c_full_n),
    .dout_c_write(entry_proc_U0_dout_c_write)
);

fft_16k_ssr2_i14_c16_t18_top_dma_in dma_in_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dma_in_U0_ap_start),
    .start_full_n(start_for_reorder_U0_full_n),
    .ap_done(dma_in_U0_ap_done),
    .ap_continue(dma_in_U0_ap_continue),
    .ap_idle(dma_in_U0_ap_idle),
    .ap_ready(dma_in_U0_ap_ready),
    .start_out(dma_in_U0_start_out),
    .start_write(dma_in_U0_start_write),
    .m_axi_gmem1_AWVALID(dma_in_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(dma_in_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(dma_in_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(dma_in_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(dma_in_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(dma_in_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(dma_in_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(dma_in_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(dma_in_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(dma_in_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(dma_in_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(dma_in_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(dma_in_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(dma_in_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(dma_in_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(dma_in_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(dma_in_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(dma_in_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(dma_in_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(dma_in_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(dma_in_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(dma_in_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(dma_in_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(dma_in_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(dma_in_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(dma_in_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(dma_in_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(dma_in_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(dma_in_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(dma_in_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(dma_in_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(dma_in_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .din(din),
    .input_stream_din(dma_in_U0_input_stream_din),
    .input_stream_num_data_valid(input_stream_num_data_valid),
    .input_stream_fifo_cap(input_stream_fifo_cap),
    .input_stream_full_n(input_stream_full_n),
    .input_stream_write(dma_in_U0_input_stream_write),
    .iter(iter),
    .iter_c25_din(dma_in_U0_iter_c25_din),
    .iter_c25_num_data_valid(iter_c25_num_data_valid),
    .iter_c25_fifo_cap(iter_c25_fifo_cap),
    .iter_c25_full_n(iter_c25_full_n),
    .iter_c25_write(dma_in_U0_iter_c25_write)
);

fft_16k_ssr2_i14_c16_t18_top_reorder reorder_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(reorder_U0_ap_start),
    .start_full_n(start_for_radix2p_U0_full_n),
    .ap_done(reorder_U0_ap_done),
    .ap_continue(reorder_U0_ap_continue),
    .ap_idle(reorder_U0_ap_idle),
    .ap_ready(reorder_U0_ap_ready),
    .start_out(reorder_U0_start_out),
    .start_write(reorder_U0_start_write),
    .input_stream_dout(input_stream_dout),
    .input_stream_num_data_valid(input_stream_num_data_valid),
    .input_stream_fifo_cap(input_stream_fifo_cap),
    .input_stream_empty_n(input_stream_empty_n),
    .input_stream_read(reorder_U0_input_stream_read),
    .reorder_out_din(reorder_U0_reorder_out_din),
    .reorder_out_num_data_valid(reorder_out_num_data_valid),
    .reorder_out_fifo_cap(reorder_out_fifo_cap),
    .reorder_out_full_n(reorder_out_full_n),
    .reorder_out_write(reorder_U0_reorder_out_write),
    .iter_dout(iter_c25_dout),
    .iter_num_data_valid(iter_c25_num_data_valid),
    .iter_fifo_cap(iter_c25_fifo_cap),
    .iter_empty_n(iter_c25_empty_n),
    .iter_read(reorder_U0_iter_read),
    .iter_c24_din(reorder_U0_iter_c24_din),
    .iter_c24_num_data_valid(iter_c24_num_data_valid),
    .iter_c24_fifo_cap(iter_c24_fifo_cap),
    .iter_c24_full_n(iter_c24_full_n),
    .iter_c24_write(reorder_U0_iter_c24_write)
);

fft_16k_ssr2_i14_c16_t18_top_radix2p radix2p_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(radix2p_U0_ap_start),
    .start_full_n(start_for_twiddle_U0_full_n),
    .ap_done(radix2p_U0_ap_done),
    .ap_continue(radix2p_U0_ap_continue),
    .ap_idle(radix2p_U0_ap_idle),
    .ap_ready(radix2p_U0_ap_ready),
    .start_out(radix2p_U0_start_out),
    .start_write(radix2p_U0_start_write),
    .reorder_out_dout(reorder_out_dout),
    .reorder_out_num_data_valid(reorder_out_num_data_valid),
    .reorder_out_fifo_cap(reorder_out_fifo_cap),
    .reorder_out_empty_n(reorder_out_empty_n),
    .reorder_out_read(radix2p_U0_reorder_out_read),
    .fft1_out_din(radix2p_U0_fft1_out_din),
    .fft1_out_num_data_valid(fft1_out_num_data_valid),
    .fft1_out_fifo_cap(fft1_out_fifo_cap),
    .fft1_out_full_n(fft1_out_full_n),
    .fft1_out_write(radix2p_U0_fft1_out_write),
    .iter_dout(iter_c24_dout),
    .iter_num_data_valid(iter_c24_num_data_valid),
    .iter_fifo_cap(iter_c24_fifo_cap),
    .iter_empty_n(iter_c24_empty_n),
    .iter_read(radix2p_U0_iter_read),
    .iter_c23_din(radix2p_U0_iter_c23_din),
    .iter_c23_num_data_valid(iter_c23_num_data_valid),
    .iter_c23_fifo_cap(iter_c23_fifo_cap),
    .iter_c23_full_n(iter_c23_full_n),
    .iter_c23_write(radix2p_U0_iter_c23_write)
);

fft_16k_ssr2_i14_c16_t18_top_twiddle twiddle_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(twiddle_U0_ap_start),
    .start_full_n(twiddle_U0_start_full_n),
    .ap_done(twiddle_U0_ap_done),
    .ap_continue(twiddle_U0_ap_continue),
    .ap_idle(twiddle_U0_ap_idle),
    .ap_ready(twiddle_U0_ap_ready),
    .start_out(twiddle_U0_start_out),
    .start_write(twiddle_U0_start_write),
    .fft1_out_dout(fft1_out_dout),
    .fft1_out_num_data_valid(fft1_out_num_data_valid),
    .fft1_out_fifo_cap(fft1_out_fifo_cap),
    .fft1_out_empty_n(fft1_out_empty_n),
    .fft1_out_read(twiddle_U0_fft1_out_read),
    .twiddle_out0_din(twiddle_U0_twiddle_out0_din),
    .twiddle_out0_num_data_valid(twiddle_out0_num_data_valid),
    .twiddle_out0_fifo_cap(twiddle_out0_fifo_cap),
    .twiddle_out0_full_n(twiddle_out0_full_n),
    .twiddle_out0_write(twiddle_U0_twiddle_out0_write),
    .twiddle_out1_din(twiddle_U0_twiddle_out1_din),
    .twiddle_out1_num_data_valid(twiddle_out1_num_data_valid),
    .twiddle_out1_fifo_cap(twiddle_out1_fifo_cap),
    .twiddle_out1_full_n(twiddle_out1_full_n),
    .twiddle_out1_write(twiddle_U0_twiddle_out1_write),
    .iter_dout(iter_c23_dout),
    .iter_num_data_valid(iter_c23_num_data_valid),
    .iter_fifo_cap(iter_c23_fifo_cap),
    .iter_empty_n(iter_c23_empty_n),
    .iter_read(twiddle_U0_iter_read),
    .iter_c21_din(twiddle_U0_iter_c21_din),
    .iter_c21_num_data_valid(iter_c21_num_data_valid),
    .iter_c21_fifo_cap(iter_c21_fifo_cap),
    .iter_c21_full_n(iter_c21_full_n),
    .iter_c21_write(twiddle_U0_iter_c21_write),
    .iter_c22_din(twiddle_U0_iter_c22_din),
    .iter_c22_num_data_valid(iter_c22_num_data_valid),
    .iter_c22_fifo_cap(iter_c22_fifo_cap),
    .iter_c22_full_n(iter_c22_full_n),
    .iter_c22_write(twiddle_U0_iter_c22_write)
);

fft_16k_ssr2_i14_c16_t18_top_fft_serial_kernel_1_wrapper fft_serial_kernel_1_wrapper_U0(
    .ap_start(fft_serial_kernel_1_wrapper_U0_ap_start),
    .start_full_n(start_for_joiner_U0_full_n),
    .start_out(fft_serial_kernel_1_wrapper_U0_start_out),
    .start_write(fft_serial_kernel_1_wrapper_U0_start_write),
    .twiddle_out0_dout(twiddle_out0_dout),
    .twiddle_out0_empty_n(twiddle_out0_empty_n),
    .twiddle_out0_read(fft_serial_kernel_1_wrapper_U0_twiddle_out0_read),
    .fft2_out0_din(fft_serial_kernel_1_wrapper_U0_fft2_out0_din),
    .fft2_out0_full_n(fft2_out0_full_n),
    .fft2_out0_write(fft_serial_kernel_1_wrapper_U0_fft2_out0_write),
    .iter_dout(iter_c22_dout),
    .iter_empty_n(iter_c22_empty_n),
    .iter_read(fft_serial_kernel_1_wrapper_U0_iter_read),
    .iter_c20_din(fft_serial_kernel_1_wrapper_U0_iter_c20_din),
    .iter_c20_full_n(iter_c20_full_n),
    .iter_c20_write(fft_serial_kernel_1_wrapper_U0_iter_c20_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(fft_serial_kernel_1_wrapper_U0_ap_done),
    .ap_ready(fft_serial_kernel_1_wrapper_U0_ap_ready),
    .ap_idle(fft_serial_kernel_1_wrapper_U0_ap_idle),
    .ap_continue(fft_serial_kernel_1_wrapper_U0_ap_continue)
);

fft_16k_ssr2_i14_c16_t18_top_fft_serial_kernel_wrapper fft_serial_kernel_wrapper_U0(
    .twiddle_out1_dout(twiddle_out1_dout),
    .twiddle_out1_empty_n(twiddle_out1_empty_n),
    .twiddle_out1_read(fft_serial_kernel_wrapper_U0_twiddle_out1_read),
    .fft2_out1_din(fft_serial_kernel_wrapper_U0_fft2_out1_din),
    .fft2_out1_full_n(fft2_out1_full_n),
    .fft2_out1_write(fft_serial_kernel_wrapper_U0_fft2_out1_write),
    .iter_dout(iter_c21_dout),
    .iter_empty_n(iter_c21_empty_n),
    .iter_read(fft_serial_kernel_wrapper_U0_iter_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_serial_kernel_wrapper_U0_ap_start),
    .ap_done(fft_serial_kernel_wrapper_U0_ap_done),
    .ap_ready(fft_serial_kernel_wrapper_U0_ap_ready),
    .ap_idle(fft_serial_kernel_wrapper_U0_ap_idle),
    .ap_continue(fft_serial_kernel_wrapper_U0_ap_continue)
);

fft_16k_ssr2_i14_c16_t18_top_joiner joiner_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(joiner_U0_ap_start),
    .ap_done(joiner_U0_ap_done),
    .ap_continue(joiner_U0_ap_continue),
    .ap_idle(joiner_U0_ap_idle),
    .ap_ready(joiner_U0_ap_ready),
    .fft2_out0_dout(fft2_out0_dout),
    .fft2_out0_num_data_valid(fft2_out0_num_data_valid),
    .fft2_out0_fifo_cap(fft2_out0_fifo_cap),
    .fft2_out0_empty_n(fft2_out0_empty_n),
    .fft2_out0_read(joiner_U0_fft2_out0_read),
    .fft2_out1_dout(fft2_out1_dout),
    .fft2_out1_num_data_valid(fft2_out1_num_data_valid),
    .fft2_out1_fifo_cap(fft2_out1_fifo_cap),
    .fft2_out1_empty_n(fft2_out1_empty_n),
    .fft2_out1_read(joiner_U0_fft2_out1_read),
    .joiner_out_din(joiner_U0_joiner_out_din),
    .joiner_out_num_data_valid(joiner_out_num_data_valid),
    .joiner_out_fifo_cap(joiner_out_fifo_cap),
    .joiner_out_full_n(joiner_out_full_n),
    .joiner_out_write(joiner_U0_joiner_out_write),
    .iter_dout(iter_c20_dout),
    .iter_num_data_valid(iter_c20_num_data_valid),
    .iter_fifo_cap(iter_c20_fifo_cap),
    .iter_empty_n(iter_c20_empty_n),
    .iter_read(joiner_U0_iter_read),
    .iter_c_din(joiner_U0_iter_c_din),
    .iter_c_num_data_valid(iter_c_num_data_valid),
    .iter_c_fifo_cap(iter_c_fifo_cap),
    .iter_c_full_n(iter_c_full_n),
    .iter_c_write(joiner_U0_iter_c_write)
);

fft_16k_ssr2_i14_c16_t18_top_dma_out dma_out_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dma_out_U0_ap_start),
    .ap_done(dma_out_U0_ap_done),
    .ap_continue(dma_out_U0_ap_continue),
    .ap_idle(dma_out_U0_ap_idle),
    .ap_ready(dma_out_U0_ap_ready),
    .joiner_out_dout(joiner_out_dout),
    .joiner_out_num_data_valid(joiner_out_num_data_valid),
    .joiner_out_fifo_cap(joiner_out_fifo_cap),
    .joiner_out_empty_n(joiner_out_empty_n),
    .joiner_out_read(dma_out_U0_joiner_out_read),
    .m_axi_gmem2_AWVALID(dma_out_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(m_axi_gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(dma_out_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(dma_out_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(dma_out_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(dma_out_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(dma_out_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(dma_out_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(dma_out_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(dma_out_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(dma_out_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(dma_out_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(dma_out_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(dma_out_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(m_axi_gmem2_WREADY),
    .m_axi_gmem2_WDATA(dma_out_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(dma_out_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(dma_out_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(dma_out_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(dma_out_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(dma_out_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(dma_out_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(dma_out_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(dma_out_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(dma_out_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(dma_out_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(dma_out_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(dma_out_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(dma_out_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(dma_out_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(dma_out_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(dma_out_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(dma_out_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(64'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(9'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(m_axi_gmem2_BVALID),
    .m_axi_gmem2_BREADY(dma_out_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(m_axi_gmem2_BRESP),
    .m_axi_gmem2_BID(m_axi_gmem2_BID),
    .m_axi_gmem2_BUSER(m_axi_gmem2_BUSER),
    .dout_dout(dout_c_dout),
    .dout_num_data_valid(dout_c_num_data_valid),
    .dout_fifo_cap(dout_c_fifo_cap),
    .dout_empty_n(dout_c_empty_n),
    .dout_read(dma_out_U0_dout_read),
    .iter_dout(iter_c_dout),
    .iter_num_data_valid(iter_c_num_data_valid),
    .iter_fifo_cap(iter_c_fifo_cap),
    .iter_empty_n(iter_c_empty_n),
    .iter_read(dma_out_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w64_d8_S dout_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_dout_c_din),
    .if_full_n(dout_c_full_n),
    .if_write(entry_proc_U0_dout_c_write),
    .if_dout(dout_c_dout),
    .if_num_data_valid(dout_c_num_data_valid),
    .if_fifo_cap(dout_c_fifo_cap),
    .if_empty_n(dout_c_empty_n),
    .if_read(dma_out_U0_dout_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w64_d2_S input_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dma_in_U0_input_stream_din),
    .if_full_n(input_stream_full_n),
    .if_write(dma_in_U0_input_stream_write),
    .if_dout(input_stream_dout),
    .if_num_data_valid(input_stream_num_data_valid),
    .if_fifo_cap(input_stream_fifo_cap),
    .if_empty_n(input_stream_empty_n),
    .if_read(reorder_U0_input_stream_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 iter_c25_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dma_in_U0_iter_c25_din),
    .if_full_n(iter_c25_full_n),
    .if_write(dma_in_U0_iter_c25_write),
    .if_dout(iter_c25_dout),
    .if_num_data_valid(iter_c25_num_data_valid),
    .if_fifo_cap(iter_c25_fifo_cap),
    .if_empty_n(iter_c25_empty_n),
    .if_read(reorder_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w64_d2_S reorder_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(reorder_U0_reorder_out_din),
    .if_full_n(reorder_out_full_n),
    .if_write(reorder_U0_reorder_out_write),
    .if_dout(reorder_out_dout),
    .if_num_data_valid(reorder_out_num_data_valid),
    .if_fifo_cap(reorder_out_fifo_cap),
    .if_empty_n(reorder_out_empty_n),
    .if_read(radix2p_U0_reorder_out_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 iter_c24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(reorder_U0_iter_c24_din),
    .if_full_n(iter_c24_full_n),
    .if_write(reorder_U0_iter_c24_write),
    .if_dout(iter_c24_dout),
    .if_num_data_valid(iter_c24_num_data_valid),
    .if_fifo_cap(iter_c24_fifo_cap),
    .if_empty_n(iter_c24_empty_n),
    .if_read(radix2p_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w64_d2_S fft1_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(radix2p_U0_fft1_out_din),
    .if_full_n(fft1_out_full_n),
    .if_write(radix2p_U0_fft1_out_write),
    .if_dout(fft1_out_dout),
    .if_num_data_valid(fft1_out_num_data_valid),
    .if_fifo_cap(fft1_out_fifo_cap),
    .if_empty_n(fft1_out_empty_n),
    .if_read(twiddle_U0_fft1_out_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 iter_c23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(radix2p_U0_iter_c23_din),
    .if_full_n(iter_c23_full_n),
    .if_write(radix2p_U0_iter_c23_write),
    .if_dout(iter_c23_dout),
    .if_num_data_valid(iter_c23_num_data_valid),
    .if_fifo_cap(iter_c23_fifo_cap),
    .if_empty_n(iter_c23_empty_n),
    .if_read(twiddle_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 twiddle_out0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(twiddle_U0_twiddle_out0_din),
    .if_full_n(twiddle_out0_full_n),
    .if_write(twiddle_U0_twiddle_out0_write),
    .if_dout(twiddle_out0_dout),
    .if_num_data_valid(twiddle_out0_num_data_valid),
    .if_fifo_cap(twiddle_out0_fifo_cap),
    .if_empty_n(twiddle_out0_empty_n),
    .if_read(fft_serial_kernel_1_wrapper_U0_twiddle_out0_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 twiddle_out1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(twiddle_U0_twiddle_out1_din),
    .if_full_n(twiddle_out1_full_n),
    .if_write(twiddle_U0_twiddle_out1_write),
    .if_dout(twiddle_out1_dout),
    .if_num_data_valid(twiddle_out1_num_data_valid),
    .if_fifo_cap(twiddle_out1_fifo_cap),
    .if_empty_n(twiddle_out1_empty_n),
    .if_read(fft_serial_kernel_wrapper_U0_twiddle_out1_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 iter_c21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(twiddle_U0_iter_c21_din),
    .if_full_n(iter_c21_full_n),
    .if_write(twiddle_U0_iter_c21_write),
    .if_dout(iter_c21_dout),
    .if_num_data_valid(iter_c21_num_data_valid),
    .if_fifo_cap(iter_c21_fifo_cap),
    .if_empty_n(iter_c21_empty_n),
    .if_read(fft_serial_kernel_wrapper_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 iter_c22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(twiddle_U0_iter_c22_din),
    .if_full_n(iter_c22_full_n),
    .if_write(twiddle_U0_iter_c22_write),
    .if_dout(iter_c22_dout),
    .if_num_data_valid(iter_c22_num_data_valid),
    .if_fifo_cap(iter_c22_fifo_cap),
    .if_empty_n(iter_c22_empty_n),
    .if_read(fft_serial_kernel_1_wrapper_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 fft2_out0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_serial_kernel_1_wrapper_U0_fft2_out0_din),
    .if_full_n(fft2_out0_full_n),
    .if_write(fft_serial_kernel_1_wrapper_U0_fft2_out0_write),
    .if_dout(fft2_out0_dout),
    .if_num_data_valid(fft2_out0_num_data_valid),
    .if_fifo_cap(fft2_out0_fifo_cap),
    .if_empty_n(fft2_out0_empty_n),
    .if_read(joiner_U0_fft2_out0_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 iter_c20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_serial_kernel_1_wrapper_U0_iter_c20_din),
    .if_full_n(iter_c20_full_n),
    .if_write(fft_serial_kernel_1_wrapper_U0_iter_c20_write),
    .if_dout(iter_c20_dout),
    .if_num_data_valid(iter_c20_num_data_valid),
    .if_fifo_cap(iter_c20_fifo_cap),
    .if_empty_n(iter_c20_empty_n),
    .if_read(joiner_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w32_d2_S_x0 fft2_out1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_serial_kernel_wrapper_U0_fft2_out1_din),
    .if_full_n(fft2_out1_full_n),
    .if_write(fft_serial_kernel_wrapper_U0_fft2_out1_write),
    .if_dout(fft2_out1_dout),
    .if_num_data_valid(fft2_out1_num_data_valid),
    .if_fifo_cap(fft2_out1_fifo_cap),
    .if_empty_n(fft2_out1_empty_n),
    .if_read(joiner_U0_fft2_out1_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w64_d2_S joiner_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(joiner_U0_joiner_out_din),
    .if_full_n(joiner_out_full_n),
    .if_write(joiner_U0_joiner_out_write),
    .if_dout(joiner_out_dout),
    .if_num_data_valid(joiner_out_num_data_valid),
    .if_fifo_cap(joiner_out_fifo_cap),
    .if_empty_n(joiner_out_empty_n),
    .if_read(dma_out_U0_joiner_out_read)
);

fft_16k_ssr2_i14_c16_t18_top_fifo_w18_d2_S iter_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(joiner_U0_iter_c_din),
    .if_full_n(iter_c_full_n),
    .if_write(joiner_U0_iter_c_write),
    .if_dout(iter_c_dout),
    .if_num_data_valid(iter_c_num_data_valid),
    .if_fifo_cap(iter_c_fifo_cap),
    .if_empty_n(iter_c_empty_n),
    .if_read(dma_out_U0_iter_read)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_dma_out_U0 start_for_dma_out_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dma_out_U0_din),
    .if_full_n(start_for_dma_out_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_dma_out_U0_dout),
    .if_empty_n(start_for_dma_out_U0_empty_n),
    .if_read(dma_out_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_reorder_U0 start_for_reorder_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_reorder_U0_din),
    .if_full_n(start_for_reorder_U0_full_n),
    .if_write(dma_in_U0_start_write),
    .if_dout(start_for_reorder_U0_dout),
    .if_empty_n(start_for_reorder_U0_empty_n),
    .if_read(reorder_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_radix2p_U0 start_for_radix2p_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_radix2p_U0_din),
    .if_full_n(start_for_radix2p_U0_full_n),
    .if_write(reorder_U0_start_write),
    .if_dout(start_for_radix2p_U0_dout),
    .if_empty_n(start_for_radix2p_U0_empty_n),
    .if_read(radix2p_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_twiddle_U0 start_for_twiddle_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_twiddle_U0_din),
    .if_full_n(start_for_twiddle_U0_full_n),
    .if_write(radix2p_U0_start_write),
    .if_dout(start_for_twiddle_U0_dout),
    .if_empty_n(start_for_twiddle_U0_empty_n),
    .if_read(twiddle_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_fft_serial_kernel_1_wrapper_U0 start_for_fft_serial_kernel_1_wrapper_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_serial_kernel_1_wrapper_U0_din),
    .if_full_n(start_for_fft_serial_kernel_1_wrapper_U0_full_n),
    .if_write(twiddle_U0_start_write),
    .if_dout(start_for_fft_serial_kernel_1_wrapper_U0_dout),
    .if_empty_n(start_for_fft_serial_kernel_1_wrapper_U0_empty_n),
    .if_read(fft_serial_kernel_1_wrapper_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_fft_serial_kernel_wrapper_U0 start_for_fft_serial_kernel_wrapper_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_serial_kernel_wrapper_U0_din),
    .if_full_n(start_for_fft_serial_kernel_wrapper_U0_full_n),
    .if_write(twiddle_U0_start_write),
    .if_dout(start_for_fft_serial_kernel_wrapper_U0_dout),
    .if_empty_n(start_for_fft_serial_kernel_wrapper_U0_empty_n),
    .if_read(fft_serial_kernel_wrapper_U0_ap_ready)
);

fft_16k_ssr2_i14_c16_t18_top_start_for_joiner_U0 start_for_joiner_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_joiner_U0_din),
    .if_full_n(start_for_joiner_U0_full_n),
    .if_write(fft_serial_kernel_1_wrapper_U0_start_write),
    .if_dout(start_for_joiner_U0_dout),
    .if_empty_n(start_for_joiner_U0_empty_n),
    .if_read(joiner_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dma_in_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dma_in_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dma_in_U0_ap_ready <= ap_sync_dma_in_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

assign ap_done = dma_out_U0_ap_done;

assign ap_idle = (twiddle_U0_ap_idle & reorder_U0_ap_idle & radix2p_U0_ap_idle & joiner_U0_ap_idle & fft_serial_kernel_wrapper_U0_ap_idle & fft_serial_kernel_1_wrapper_U0_ap_idle & entry_proc_U0_ap_idle & dma_out_U0_ap_idle & dma_in_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_dma_in_U0_ap_ready = (dma_in_U0_ap_ready | ap_sync_reg_dma_in_U0_ap_ready);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_entry_proc_U0_ap_ready & ap_sync_dma_in_U0_ap_ready);

assign dma_in_U0_ap_continue = 1'b1;

assign dma_in_U0_ap_start = ((ap_sync_reg_dma_in_U0_ap_ready ^ 1'b1) & ap_start);

assign dma_out_U0_ap_continue = ap_continue;

assign dma_out_U0_ap_start = start_for_dma_out_U0_empty_n;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign fft_serial_kernel_1_wrapper_U0_ap_continue = 1'b1;

assign fft_serial_kernel_1_wrapper_U0_ap_start = start_for_fft_serial_kernel_1_wrapper_U0_empty_n;

assign fft_serial_kernel_wrapper_U0_ap_continue = 1'b1;

assign fft_serial_kernel_wrapper_U0_ap_start = start_for_fft_serial_kernel_wrapper_U0_empty_n;

assign joiner_U0_ap_continue = 1'b1;

assign joiner_U0_ap_start = start_for_joiner_U0_empty_n;

assign m_axi_gmem1_ARADDR = dma_in_U0_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = dma_in_U0_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = dma_in_U0_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = dma_in_U0_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = dma_in_U0_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = dma_in_U0_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = dma_in_U0_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = dma_in_U0_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = dma_in_U0_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = dma_in_U0_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = dma_in_U0_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_ARVALID = dma_in_U0_m_axi_gmem1_ARVALID;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_RREADY = dma_in_U0_m_axi_gmem1_RREADY;

assign m_axi_gmem1_WDATA = 64'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 8'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign m_axi_gmem2_ARADDR = 64'd0;

assign m_axi_gmem2_ARBURST = 2'd0;

assign m_axi_gmem2_ARCACHE = 4'd0;

assign m_axi_gmem2_ARID = 1'd0;

assign m_axi_gmem2_ARLEN = 32'd0;

assign m_axi_gmem2_ARLOCK = 2'd0;

assign m_axi_gmem2_ARPROT = 3'd0;

assign m_axi_gmem2_ARQOS = 4'd0;

assign m_axi_gmem2_ARREGION = 4'd0;

assign m_axi_gmem2_ARSIZE = 3'd0;

assign m_axi_gmem2_ARUSER = 1'd0;

assign m_axi_gmem2_ARVALID = 1'b0;

assign m_axi_gmem2_AWADDR = dma_out_U0_m_axi_gmem2_AWADDR;

assign m_axi_gmem2_AWBURST = dma_out_U0_m_axi_gmem2_AWBURST;

assign m_axi_gmem2_AWCACHE = dma_out_U0_m_axi_gmem2_AWCACHE;

assign m_axi_gmem2_AWID = dma_out_U0_m_axi_gmem2_AWID;

assign m_axi_gmem2_AWLEN = dma_out_U0_m_axi_gmem2_AWLEN;

assign m_axi_gmem2_AWLOCK = dma_out_U0_m_axi_gmem2_AWLOCK;

assign m_axi_gmem2_AWPROT = dma_out_U0_m_axi_gmem2_AWPROT;

assign m_axi_gmem2_AWQOS = dma_out_U0_m_axi_gmem2_AWQOS;

assign m_axi_gmem2_AWREGION = dma_out_U0_m_axi_gmem2_AWREGION;

assign m_axi_gmem2_AWSIZE = dma_out_U0_m_axi_gmem2_AWSIZE;

assign m_axi_gmem2_AWUSER = dma_out_U0_m_axi_gmem2_AWUSER;

assign m_axi_gmem2_AWVALID = dma_out_U0_m_axi_gmem2_AWVALID;

assign m_axi_gmem2_BREADY = dma_out_U0_m_axi_gmem2_BREADY;

assign m_axi_gmem2_RREADY = 1'b0;

assign m_axi_gmem2_WDATA = dma_out_U0_m_axi_gmem2_WDATA;

assign m_axi_gmem2_WID = dma_out_U0_m_axi_gmem2_WID;

assign m_axi_gmem2_WLAST = dma_out_U0_m_axi_gmem2_WLAST;

assign m_axi_gmem2_WSTRB = dma_out_U0_m_axi_gmem2_WSTRB;

assign m_axi_gmem2_WUSER = dma_out_U0_m_axi_gmem2_WUSER;

assign m_axi_gmem2_WVALID = dma_out_U0_m_axi_gmem2_WVALID;

assign radix2p_U0_ap_continue = 1'b1;

assign radix2p_U0_ap_start = start_for_radix2p_U0_empty_n;

assign reorder_U0_ap_continue = 1'b1;

assign reorder_U0_ap_start = start_for_reorder_U0_empty_n;

assign start_for_dma_out_U0_din = 1'b1;

assign start_for_fft_serial_kernel_1_wrapper_U0_din = 1'b1;

assign start_for_fft_serial_kernel_wrapper_U0_din = 1'b1;

assign start_for_joiner_U0_din = 1'b1;

assign start_for_radix2p_U0_din = 1'b1;

assign start_for_reorder_U0_din = 1'b1;

assign start_for_twiddle_U0_din = 1'b1;

assign twiddle_U0_ap_continue = 1'b1;

assign twiddle_U0_ap_start = start_for_twiddle_U0_empty_n;

assign twiddle_U0_start_full_n = (start_for_fft_serial_kernel_wrapper_U0_full_n & start_for_fft_serial_kernel_1_wrapper_U0_full_n);

endmodule //fft_16k_ssr2_i14_c16_t18_top_fft_core
