// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_16k_ssr2_i14_c16_t18_top_joiner (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fft2_out0_dout,
        fft2_out0_num_data_valid,
        fft2_out0_fifo_cap,
        fft2_out0_empty_n,
        fft2_out0_read,
        fft2_out1_dout,
        fft2_out1_num_data_valid,
        fft2_out1_fifo_cap,
        fft2_out1_empty_n,
        fft2_out1_read,
        joiner_out_din,
        joiner_out_num_data_valid,
        joiner_out_fifo_cap,
        joiner_out_full_n,
        joiner_out_write,
        iter_dout,
        iter_num_data_valid,
        iter_fifo_cap,
        iter_empty_n,
        iter_read,
        iter_c_din,
        iter_c_num_data_valid,
        iter_c_fifo_cap,
        iter_c_full_n,
        iter_c_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] fft2_out0_dout;
input  [2:0] fft2_out0_num_data_valid;
input  [2:0] fft2_out0_fifo_cap;
input   fft2_out0_empty_n;
output   fft2_out0_read;
input  [31:0] fft2_out1_dout;
input  [2:0] fft2_out1_num_data_valid;
input  [2:0] fft2_out1_fifo_cap;
input   fft2_out1_empty_n;
output   fft2_out1_read;
output  [63:0] joiner_out_din;
input  [2:0] joiner_out_num_data_valid;
input  [2:0] joiner_out_fifo_cap;
input   joiner_out_full_n;
output   joiner_out_write;
input  [31:0] iter_dout;
input  [2:0] iter_num_data_valid;
input  [2:0] iter_fifo_cap;
input   iter_empty_n;
output   iter_read;
output  [17:0] iter_c_din;
input  [2:0] iter_c_num_data_valid;
input  [2:0] iter_c_fifo_cap;
input   iter_c_full_n;
output   iter_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fft2_out0_read;
reg fft2_out1_read;
reg joiner_out_write;
reg iter_read;
reg iter_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    iter_blk_n;
reg    iter_c_blk_n;
reg   [31:0] iter_4_reg_97;
reg    ap_block_state1;
wire   [44:0] tmp_fu_89_p3;
reg   [44:0] tmp_reg_102;
wire    ap_CS_fsm_state2;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_idle;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_ready;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_fft2_out0_read;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_fft2_out1_read;
wire   [63:0] grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_joiner_out_din;
wire    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_joiner_out_write;
reg    grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start_reg = 1'b0;
end

fft_16k_ssr2_i14_c16_t18_top_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2 grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start),
    .ap_done(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done),
    .ap_idle(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_idle),
    .ap_ready(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_ready),
    .fft2_out0_dout(fft2_out0_dout),
    .fft2_out0_num_data_valid(3'd0),
    .fft2_out0_fifo_cap(3'd0),
    .fft2_out0_empty_n(fft2_out0_empty_n),
    .fft2_out0_read(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_fft2_out0_read),
    .fft2_out1_dout(fft2_out1_dout),
    .fft2_out1_num_data_valid(3'd0),
    .fft2_out1_fifo_cap(3'd0),
    .fft2_out1_empty_n(fft2_out1_empty_n),
    .fft2_out1_read(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_fft2_out1_read),
    .joiner_out_din(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_joiner_out_din),
    .joiner_out_num_data_valid(3'd0),
    .joiner_out_fifo_cap(3'd0),
    .joiner_out_full_n(joiner_out_full_n),
    .joiner_out_write(grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_joiner_out_write),
    .bound(tmp_reg_102)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start_reg <= 1'b1;
        end else if ((grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_ready == 1'b1)) begin
            grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_4_reg_97 <= iter_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_102[44 : 13] <= tmp_fu_89_p3[44 : 13];
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fft2_out0_read = grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_fft2_out0_read;
    end else begin
        fft2_out0_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fft2_out1_read = grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_fft2_out1_read;
    end else begin
        fft2_out1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_blk_n = iter_empty_n;
    end else begin
        iter_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_c_blk_n = iter_c_full_n;
    end else begin
        iter_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_c_write = 1'b1;
    end else begin
        iter_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_read = 1'b1;
    end else begin
        iter_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        joiner_out_write = grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_joiner_out_write;
    end else begin
        joiner_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (iter_c_full_n == 1'b0) | (iter_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start = grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_ap_start_reg;

assign iter_c_din = iter_dout[17:0];

assign joiner_out_din = grp_joiner_Pipeline_VITIS_LOOP_285_1_VITIS_LOOP_288_2_fu_73_joiner_out_din;

assign tmp_fu_89_p3 = {{iter_4_reg_97}, {13'd0}};

always @ (posedge ap_clk) begin
    tmp_reg_102[12:0] <= 13'b0000000000000;
end

endmodule //fft_16k_ssr2_i14_c16_t18_top_joiner
