// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fft_16_ssr1_i16_c16_t16_top_dma_out (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        fft_out_dout,
        fft_out_num_data_valid,
        fft_out_fifo_cap,
        fft_out_empty_n,
        fft_out_read,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        dout_dout,
        dout_num_data_valid,
        dout_fifo_cap,
        dout_empty_n,
        dout_read,
        iter_dout,
        iter_num_data_valid,
        iter_fifo_cap,
        iter_empty_n,
        iter_read
);

parameter    ap_ST_fsm_state1 = 73'd1;
parameter    ap_ST_fsm_state2 = 73'd2;
parameter    ap_ST_fsm_state3 = 73'd4;
parameter    ap_ST_fsm_state4 = 73'd8;
parameter    ap_ST_fsm_state5 = 73'd16;
parameter    ap_ST_fsm_state6 = 73'd32;
parameter    ap_ST_fsm_state7 = 73'd64;
parameter    ap_ST_fsm_state8 = 73'd128;
parameter    ap_ST_fsm_state9 = 73'd256;
parameter    ap_ST_fsm_state10 = 73'd512;
parameter    ap_ST_fsm_state11 = 73'd1024;
parameter    ap_ST_fsm_state12 = 73'd2048;
parameter    ap_ST_fsm_state13 = 73'd4096;
parameter    ap_ST_fsm_state14 = 73'd8192;
parameter    ap_ST_fsm_state15 = 73'd16384;
parameter    ap_ST_fsm_state16 = 73'd32768;
parameter    ap_ST_fsm_state17 = 73'd65536;
parameter    ap_ST_fsm_state18 = 73'd131072;
parameter    ap_ST_fsm_state19 = 73'd262144;
parameter    ap_ST_fsm_state20 = 73'd524288;
parameter    ap_ST_fsm_state21 = 73'd1048576;
parameter    ap_ST_fsm_state22 = 73'd2097152;
parameter    ap_ST_fsm_state23 = 73'd4194304;
parameter    ap_ST_fsm_state24 = 73'd8388608;
parameter    ap_ST_fsm_state25 = 73'd16777216;
parameter    ap_ST_fsm_state26 = 73'd33554432;
parameter    ap_ST_fsm_state27 = 73'd67108864;
parameter    ap_ST_fsm_state28 = 73'd134217728;
parameter    ap_ST_fsm_state29 = 73'd268435456;
parameter    ap_ST_fsm_state30 = 73'd536870912;
parameter    ap_ST_fsm_state31 = 73'd1073741824;
parameter    ap_ST_fsm_state32 = 73'd2147483648;
parameter    ap_ST_fsm_state33 = 73'd4294967296;
parameter    ap_ST_fsm_state34 = 73'd8589934592;
parameter    ap_ST_fsm_state35 = 73'd17179869184;
parameter    ap_ST_fsm_state36 = 73'd34359738368;
parameter    ap_ST_fsm_state37 = 73'd68719476736;
parameter    ap_ST_fsm_state38 = 73'd137438953472;
parameter    ap_ST_fsm_state39 = 73'd274877906944;
parameter    ap_ST_fsm_state40 = 73'd549755813888;
parameter    ap_ST_fsm_state41 = 73'd1099511627776;
parameter    ap_ST_fsm_state42 = 73'd2199023255552;
parameter    ap_ST_fsm_state43 = 73'd4398046511104;
parameter    ap_ST_fsm_state44 = 73'd8796093022208;
parameter    ap_ST_fsm_state45 = 73'd17592186044416;
parameter    ap_ST_fsm_state46 = 73'd35184372088832;
parameter    ap_ST_fsm_state47 = 73'd70368744177664;
parameter    ap_ST_fsm_state48 = 73'd140737488355328;
parameter    ap_ST_fsm_state49 = 73'd281474976710656;
parameter    ap_ST_fsm_state50 = 73'd562949953421312;
parameter    ap_ST_fsm_state51 = 73'd1125899906842624;
parameter    ap_ST_fsm_state52 = 73'd2251799813685248;
parameter    ap_ST_fsm_state53 = 73'd4503599627370496;
parameter    ap_ST_fsm_state54 = 73'd9007199254740992;
parameter    ap_ST_fsm_state55 = 73'd18014398509481984;
parameter    ap_ST_fsm_state56 = 73'd36028797018963968;
parameter    ap_ST_fsm_state57 = 73'd72057594037927936;
parameter    ap_ST_fsm_state58 = 73'd144115188075855872;
parameter    ap_ST_fsm_state59 = 73'd288230376151711744;
parameter    ap_ST_fsm_state60 = 73'd576460752303423488;
parameter    ap_ST_fsm_state61 = 73'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 73'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 73'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 73'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 73'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 73'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 73'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 73'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 73'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 73'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 73'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 73'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 73'd4722366482869645213696;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] fft_out_dout;
input  [2:0] fft_out_num_data_valid;
input  [2:0] fft_out_fifo_cap;
input   fft_out_empty_n;
output   fft_out_read;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [511:0] m_axi_gmem2_WDATA;
output  [63:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [511:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [8:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] dout_dout;
input  [2:0] dout_num_data_valid;
input  [2:0] dout_fifo_cap;
input   dout_empty_n;
output   dout_read;
input  [27:0] iter_dout;
input  [2:0] iter_num_data_valid;
input  [2:0] iter_fifo_cap;
input   iter_empty_n;
output   iter_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg fft_out_read;
reg m_axi_gmem2_AWVALID;
reg[63:0] m_axi_gmem2_AWADDR;
reg[0:0] m_axi_gmem2_AWID;
reg[31:0] m_axi_gmem2_AWLEN;
reg[2:0] m_axi_gmem2_AWSIZE;
reg[1:0] m_axi_gmem2_AWBURST;
reg[1:0] m_axi_gmem2_AWLOCK;
reg[3:0] m_axi_gmem2_AWCACHE;
reg[2:0] m_axi_gmem2_AWPROT;
reg[3:0] m_axi_gmem2_AWQOS;
reg[3:0] m_axi_gmem2_AWREGION;
reg[0:0] m_axi_gmem2_AWUSER;
reg m_axi_gmem2_WVALID;
reg m_axi_gmem2_BREADY;
reg dout_read;
reg iter_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [72:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem2_blk_n_AW;
wire    ap_CS_fsm_state3;
reg    gmem2_blk_n_B;
wire    ap_CS_fsm_state73;
reg    dout_blk_n;
reg    iter_blk_n;
reg   [27:0] iter_1_reg_159;
reg    ap_block_state1;
wire   [26:0] empty_fu_111_p1;
reg   [26:0] empty_reg_165;
reg   [57:0] trunc_ln_reg_170;
wire   [26:0] empty_37_fu_130_p3;
reg   [26:0] empty_37_reg_176;
wire    ap_CS_fsm_state2;
wire   [31:0] mul_i_fu_151_p3;
reg   [31:0] mul_i_reg_186;
wire    ap_CS_fsm_state4;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_done;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_idle;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_ready;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_fft_out_read;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWVALID;
wire   [63:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWADDR;
wire   [0:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWID;
wire   [31:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWLEN;
wire   [2:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWSIZE;
wire   [1:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWBURST;
wire   [1:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWLOCK;
wire   [3:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWCACHE;
wire   [2:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWPROT;
wire   [3:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWQOS;
wire   [3:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWREGION;
wire   [0:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWUSER;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WVALID;
wire   [511:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WDATA;
wire   [63:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WSTRB;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WLAST;
wire   [0:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WID;
wire   [0:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WUSER;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARVALID;
wire   [63:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARADDR;
wire   [0:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARID;
wire   [31:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARLEN;
wire   [2:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARSIZE;
wire   [1:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARBURST;
wire   [1:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARLOCK;
wire   [3:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARCACHE;
wire   [2:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARPROT;
wire   [3:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARQOS;
wire   [3:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARREGION;
wire   [0:0] grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARUSER;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_RREADY;
wire    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_BREADY;
reg    grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start_reg;
wire    ap_CS_fsm_state5;
wire  signed [63:0] sext_ln78_fu_137_p1;
wire   [31:0] zext_ln78_fu_147_p1;
wire   [0:0] icmp_ln78_fu_125_p2;
reg   [72:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
reg    ap_ST_fsm_state73_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 73'd1;
#0 grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start_reg = 1'b0;
end

fft_16_ssr1_i16_c16_t16_top_dma_out_Pipeline_VITIS_LOOP_78_1 grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start),
    .ap_done(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_done),
    .ap_idle(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_idle),
    .ap_ready(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_ready),
    .fft_out_dout(fft_out_dout),
    .fft_out_num_data_valid(3'd0),
    .fft_out_fifo_cap(3'd0),
    .fft_out_empty_n(fft_out_empty_n),
    .fft_out_read(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_fft_out_read),
    .m_axi_gmem2_AWVALID(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(m_axi_gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(m_axi_gmem2_WREADY),
    .m_axi_gmem2_WDATA(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(512'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RFIFONUM(9'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(m_axi_gmem2_BVALID),
    .m_axi_gmem2_BREADY(grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(m_axi_gmem2_BRESP),
    .m_axi_gmem2_BID(m_axi_gmem2_BID),
    .m_axi_gmem2_BUSER(m_axi_gmem2_BUSER),
    .mul_i(mul_i_reg_186),
    .sext_ln78(trunc_ln_reg_170)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem2_BVALID == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_ready == 1'b1)) begin
            grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        empty_37_reg_176 <= empty_37_fu_130_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        empty_reg_165 <= empty_fu_111_p1;
        iter_1_reg_159 <= iter_dout;
        trunc_ln_reg_170 <= {{dout_dout[63:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        mul_i_reg_186[31 : 4] <= mul_i_fu_151_p3[31 : 4];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem2_AWREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

always @ (*) begin
    if ((grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem2_BVALID == 1'b0)) begin
        ap_ST_fsm_state73_blk = 1'b1;
    end else begin
        ap_ST_fsm_state73_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem2_BVALID == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem2_BVALID == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        dout_blk_n = dout_empty_n;
    end else begin
        dout_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        dout_read = 1'b1;
    end else begin
        dout_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        fft_out_read = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_fft_out_read;
    end else begin
        fft_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem2_blk_n_AW = m_axi_gmem2_AWREADY;
    end else begin
        gmem2_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        gmem2_blk_n_B = m_axi_gmem2_BVALID;
    end else begin
        gmem2_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        iter_blk_n = iter_empty_n;
    end else begin
        iter_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        iter_read = 1'b1;
    end else begin
        iter_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (m_axi_gmem2_AWREADY == 1'b1))) begin
        m_axi_gmem2_AWADDR = sext_ln78_fu_137_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWADDR = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWADDR;
    end else begin
        m_axi_gmem2_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWBURST = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWBURST;
    end else begin
        m_axi_gmem2_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWCACHE = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWCACHE;
    end else begin
        m_axi_gmem2_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWID = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWID;
    end else begin
        m_axi_gmem2_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (m_axi_gmem2_AWREADY == 1'b1))) begin
        m_axi_gmem2_AWLEN = zext_ln78_fu_147_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWLEN = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWLEN;
    end else begin
        m_axi_gmem2_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWLOCK = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWLOCK;
    end else begin
        m_axi_gmem2_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWPROT = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWPROT;
    end else begin
        m_axi_gmem2_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWQOS = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWQOS;
    end else begin
        m_axi_gmem2_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWREGION = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWREGION;
    end else begin
        m_axi_gmem2_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWSIZE = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWSIZE;
    end else begin
        m_axi_gmem2_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWUSER = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWUSER;
    end else begin
        m_axi_gmem2_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (m_axi_gmem2_AWREADY == 1'b1))) begin
        m_axi_gmem2_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_AWVALID = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_AWVALID;
    end else begin
        m_axi_gmem2_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem2_BVALID == 1'b1))) begin
        m_axi_gmem2_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_BREADY = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_BREADY;
    end else begin
        m_axi_gmem2_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        m_axi_gmem2_WVALID = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WVALID;
    end else begin
        m_axi_gmem2_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (m_axi_gmem2_AWREADY == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if (((1'b1 == ap_CS_fsm_state73) & (m_axi_gmem2_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | (iter_empty_n == 1'b0) | (dout_empty_n == 1'b0));
end

assign empty_37_fu_130_p3 = ((icmp_ln78_fu_125_p2[0:0] == 1'b1) ? empty_reg_165 : 27'd0);

assign empty_fu_111_p1 = iter_dout[26:0];

assign grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_ap_start_reg;

assign icmp_ln78_fu_125_p2 = (($signed(iter_1_reg_159) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign m_axi_gmem2_ARADDR = 64'd0;

assign m_axi_gmem2_ARBURST = 2'd0;

assign m_axi_gmem2_ARCACHE = 4'd0;

assign m_axi_gmem2_ARID = 1'd0;

assign m_axi_gmem2_ARLEN = 32'd0;

assign m_axi_gmem2_ARLOCK = 2'd0;

assign m_axi_gmem2_ARPROT = 3'd0;

assign m_axi_gmem2_ARQOS = 4'd0;

assign m_axi_gmem2_ARREGION = 4'd0;

assign m_axi_gmem2_ARSIZE = 3'd0;

assign m_axi_gmem2_ARUSER = 1'd0;

assign m_axi_gmem2_ARVALID = 1'b0;

assign m_axi_gmem2_RREADY = 1'b0;

assign m_axi_gmem2_WDATA = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WDATA;

assign m_axi_gmem2_WID = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WID;

assign m_axi_gmem2_WLAST = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WLAST;

assign m_axi_gmem2_WSTRB = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WSTRB;

assign m_axi_gmem2_WUSER = grp_dma_out_Pipeline_VITIS_LOOP_78_1_fu_101_m_axi_gmem2_WUSER;

assign mul_i_fu_151_p3 = {{iter_1_reg_159}, {4'd0}};

assign sext_ln78_fu_137_p1 = $signed(trunc_ln_reg_170);

assign zext_ln78_fu_147_p1 = empty_37_reg_176;

always @ (posedge ap_clk) begin
    mul_i_reg_186[3:0] <= 4'b0000;
end

endmodule //fft_16_ssr1_i16_c16_t16_top_dma_out
